/*File generated by PreProcessor.py*/


#include "funcoes.h"


node_jogo *func_a(int cont, hash_table_jogo *syst_jogos, hash_table_equipa *syst_eq, node_jogo *head_lista_jogos)
{
  char buf_jg[1023];
  char buf_t1[1023];
  char buf_t2[1023];
  int s1;
  int s2;
  node_jogo *tmp;
  node_equipa *tmp2;
  for (int buf_jg_index = 0; buf_jg_index < 10; buf_jg_index++)
  {
    buf_jg[buf_jg_index] = new_sym_var(sizeof(char) * 8);
  }

  buf_jg[10 - 1] = '\0';
  for (int buf_t1_index = 0; buf_t1_index < 10; buf_t1_index++)
  {
    buf_t1[buf_t1_index] = new_sym_var(sizeof(char) * 8);
  }

  buf_t1[10 - 1] = '\0';
  for (int buf_t2_index = 0; buf_t2_index < 10; buf_t2_index++)
  {
    buf_t2[buf_t2_index] = new_sym_var(sizeof(char) * 8);
  }

  buf_t2[10 - 1] = '\0';
  s1 = new_sym_var(sizeof(int) * 8);
  s2 = new_sym_var(sizeof(int) * 8);
  if (encontra_hash_jg(syst_jogos, buf_jg) != 0)
  {
    printf("%d Jogo existente.\n", cont);
  }
  else
  {
    if ((encontra_hash_eq(syst_eq, buf_t1) == 0) || (encontra_hash_eq(syst_eq, buf_t2) == 0))
    {
      printf("%d Equipa inexistente.\n", cont);
    }
    else
    {
      tmp = cria_node_jg(buf_jg, buf_t1, buf_t2, s1, s2);
      if (s1 > s2)
      {
        tmp2 = encontra_hash_eq(syst_eq, buf_t1);
        tmp2->vitorias++;
      }
      else
      {
        if (s1 < s2)
        {
          tmp2 = encontra_hash_eq(syst_eq, buf_t2);
          tmp2->vitorias++;
        }
        else
        {
          
        }

      }

      insere_jogo_hash(syst_jogos, tmp);
      head_lista_jogos = _insere_jogo_lista(head_lista_jogos, tmp, &syst_jogos->last);
    }

  }

  return head_lista_jogos;
}

void func_l(int cont, node_jogo *head_lista_jogos)
{
  printlist_jogo(head_lista_jogos, cont);
}

void func_p(int cont, hash_table_jogo *syst_jogos)
{
  node_jogo *tmp;
  char buf_jg[1023];
  for (int buf_jg_index = 0; buf_jg_index < 10; buf_jg_index++)
  {
    buf_jg[buf_jg_index] = new_sym_var(sizeof(char) * 8);
  }

  buf_jg[10 - 1] = '\0';
  tmp = encontra_hash_jg(syst_jogos, buf_jg);
  if (tmp == 0)
  {
    printf("%d Jogo inexistente.\n", cont);
  }
  else
  {
    printf("%d %s %s %s %d %d\n", cont, tmp->nome, tmp->t1, tmp->t2, tmp->s1, tmp->s2);
  }

}

node_jogo *func_r(int cont, hash_table_jogo *syst_jogos, hash_table_equipa *syst_eq, node_jogo *head_lista_jogos)
{
  node_jogo *tmp;
  node_equipa *tmp2;
  char buf_jg[1023];
  for (int buf_jg_index = 0; buf_jg_index < 10; buf_jg_index++)
  {
    buf_jg[buf_jg_index] = new_sym_var(sizeof(char) * 8);
  }

  buf_jg[10 - 1] = '\0';
  tmp = encontra_hash_jg(syst_jogos, buf_jg);
  if (tmp == 0)
  {
    printf("%d Jogo inexistente.\n", cont);
  }
  else
  {
    if (tmp->s1 > tmp->s2)
    {
      tmp2 = encontra_hash_eq(syst_eq, tmp->t1);
      tmp2->vitorias--;
    }
    else
    {
      if (tmp->s2 > tmp->s1)
      {
        tmp2 = encontra_hash_eq(syst_eq, tmp->t2);
        tmp2->vitorias--;
      }
      else
      {
        
      }

    }

    head_lista_jogos = remove_node_list(head_lista_jogos, tmp, &syst_jogos->last);
    remove_jogo_hash(syst_jogos, buf_jg);
  }

  return head_lista_jogos;
}

void func_s(int cont, hash_table_jogo *syst_jogos, hash_table_equipa *syst_eq)
{
  node_jogo *tmp;
  node_equipa *t1;
  node_equipa *t2;
  char buf_jg[1023];
  int estado1 = 0;
  int estado2 = 0;
  int s1;
  int s2;
  for (int buf_jg_index = 0; buf_jg_index < 10; buf_jg_index++)
  {
    buf_jg[buf_jg_index] = new_sym_var(sizeof(char) * 8);
  }

  buf_jg[10 - 1] = '\0';
  s1 = new_sym_var(sizeof(int) * 8);
  s2 = new_sym_var(sizeof(int) * 8);
  tmp = encontra_hash_jg(syst_jogos, buf_jg);
  if (tmp == 0)
  {
    printf("%d Jogo inexistente.\n", cont);
  }
  else
  {
    t1 = encontra_hash_eq(syst_eq, tmp->t1);
    t2 = encontra_hash_eq(syst_eq, tmp->t2);
    if (tmp->s1 > tmp->s2)
    {
      estado1 = 1;
    }
    else
    {
      if (tmp->s1 < tmp->s2)
      {
        estado2 = 1;
      }
      else
      {
        
      }

    }

    if (estado1)
    {
      if (s1 == s2)
      {
        diminui_vitorias(t1);
      }
      else
      {
        if (s2 > s1)
        {
          diminui_vitorias(t1);
          aumenta_vitorias(t2);
        }
        else
        {
          
        }

      }

    }
    else
    {
      if (estado2)
      {
        if (s1 == s2)
        {
          diminui_vitorias(t2);
        }
        else
        {
          if (s1 > s2)
          {
            aumenta_vitorias(t1);
            diminui_vitorias(t2);
          }
          else
          {
            
          }

        }

      }
      else
      {
        if (s1 > s2)
        {
          aumenta_vitorias(t1);
        }
        else
        {
          if (s2 > s1)
          {
            aumenta_vitorias(t2);
          }
          else
          {
            
          }

        }

      }

    }

    tmp->s1 = s1;
    tmp->s2 = s2;
  }

}

void func_A(int cont, hash_table_equipa *syst_eq)
{
  node_equipa *tmp;
  char buf_t1[1023];
  for (int buf_t1_index = 0; buf_t1_index < 10; buf_t1_index++)
  {
    buf_t1[buf_t1_index] = new_sym_var(sizeof(char) * 8);
  }

  buf_t1[10 - 1] = '\0';
  if (encontra_hash_eq(syst_eq, buf_t1) != 0)
  {
    printf("%d Equipa existente.\n", cont);
  }
  else
  {
    tmp = cria_node_eq(buf_t1);
    insere_eq_hash(syst_eq, tmp);
  }

}

void func_P(int cont, hash_table_equipa *syst_eq)
{
  node_equipa *tmp;
  char buf_t1[1023];
  for (int buf_t1_index = 0; buf_t1_index < 10; buf_t1_index++)
  {
    buf_t1[buf_t1_index] = new_sym_var(sizeof(char) * 8);
  }

  buf_t1[10 - 1] = '\0';
  tmp = encontra_hash_eq(syst_eq, buf_t1);
  if (tmp == 0)
  {
    printf("%d Equipa inexistente.\n", cont);
  }
  else
  {
    printf("%d %s %d\n", cont, tmp->nome, tmp->vitorias);
  }

}

void func_g(int cont, hash_table_equipa *syst_eq)
{
  size_t i;
  int vitorias = 0;
  int k = 0;
  int j;
  int contem = 0;
  char *vetor[1237];
  node_equipa *tmp;
  for (i = 0; i < 1237; i++)
  {
    tmp = syst_eq->tb[i];
    while (tmp != 0)
    {
      contem = 1;
      if (tmp->vitorias == vitorias)
      {
        vetor[k] = tmp->nome;
        k++;
      }
      else
      {
        if (tmp->vitorias > vitorias)
        {
          k = 0;
          vetor[k] = tmp->nome;
          k++;
          vitorias = tmp->vitorias;
        }
        else
        {
          
        }

      }

      tmp = tmp->next;
    }

  }

  if (contem)
  {
    qsort(vetor, k, sizeof(char *), compara);
    printf("%d Melhores %d\n", cont, vitorias);
    for (j = 0; j < k; j++)
    {
      printf("%d * %s\n", cont, vetor[j]);
    }

  }
  else
  {
    
  }

}

