/*File generated by PreProcessor.py*/


#include "hash.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>


int hashU(char *v, int m)
{
  int h;
  int a = 31415;
  int b = 27183;
  for (h = 0; (*v) != '\0'; v++, a = (a * b) % (m - 1))
    h = ((a * h) + (*v)) % m;

  return h;
}

char *str_dup(char *buffer)
{
  char *str;
  str = (char *) malloc((sizeof(char)) * (strlen(buffer) + 1));
  strcpy(str, buffer);
  return str;
}

pListas *inicializa_listas(pListas *listas, int m)
{
  int i;
  listas = (pListas *) malloc(m * (sizeof(pListas)));
  for (i = 0; i < m; i++)
  {
    listas[i] = (pListas) malloc(sizeof(struct Listas));
    listas[i]->head_equipas = 0;
    listas[i]->head_jogos = 0;
    listas[i]->tail_equipas = 0;
    listas[i]->tail_jogos = 0;
  }

  return listas;
}

pLst_Ord inicializa_lista_ordenada(pLst_Ord lista_ordenada)
{
  lista_ordenada = (pLst_Ord) malloc(sizeof(struct Lst_Ord));
  lista_ordenada->head_jogos = 0;
  lista_ordenada->tail_jogos = 0;
  lista_ordenada->lista_equipas = (pEquipa *) calloc(10000, sizeof(pEquipa));
  lista_ordenada->cont_equipas = 0;
  return lista_ordenada;
}

void insere_equipa(pListas lista_equipas, link_equipa nova_equipa)
{
  if (lista_equipas->head_equipas == 0)
  {
    lista_equipas->head_equipas = nova_equipa;
    lista_equipas->tail_equipas = nova_equipa;
    return;
  }
  else
  {
    
  }

  lista_equipas->tail_equipas->next = nova_equipa;
  lista_equipas->tail_equipas = nova_equipa;
  return;
}

void insere_jogo_hash(pListas lista_jogos, link_jogo novo_jogo)
{
  if (lista_jogos->head_jogos == 0)
  {
    lista_jogos->head_jogos = novo_jogo;
    lista_jogos->tail_jogos = novo_jogo;
    return;
  }
  else
  {
    
  }

  lista_jogos->tail_jogos->next = novo_jogo;
  lista_jogos->tail_jogos = novo_jogo;
  return;
}

void insere_jogo_lista_ordenada(pLst_Ord lista_jogos, link_jogo novo_jogo)
{
  if (lista_jogos->head_jogos == 0)
  {
    lista_jogos->head_jogos = novo_jogo;
    lista_jogos->tail_jogos = novo_jogo;
    return;
  }
  else
  {
    
  }

  lista_jogos->tail_jogos->next = novo_jogo;
  lista_jogos->tail_jogos = novo_jogo;
  return;
}

link_equipa procura_equipa(pListas *listas, char *nome, int m)
{
  int index = hashU(nome, m);
  link_equipa link;
  if (listas[index]->head_equipas == 0)
  {
    return 0;
  }
  else
  {
    
  }

  for (link = listas[index]->head_equipas; link != 0; link = link->next)
  {
    if (!strcmp(nome, link->equipa->nome))
    {
      return link;
    }
    else
    {
      
    }

  }

  return 0;
}

link_jogo procura_jogo(pListas *listas, char *nome, int m)
{
  int index = hashU(nome, m);
  link_jogo link;
  if (listas[index]->head_jogos == 0)
  {
    return 0;
  }
  else
  {
    
  }

  for (link = listas[index]->head_jogos; link != 0; link = link->next)
  {
    if (!strcmp(nome, link->jogo->nome))
    {
      return link;
    }
    else
    {
      
    }

  }

  return 0;
}

void elimina_hash(pListas lista_jogos, char *nome)
{
  link_jogo link;
  link_jogo prev;
  for (link = lista_jogos->head_jogos, prev = 0; link != 0; prev = link, link = link->next)
  {
    if (!strcmp(link->jogo->nome, nome))
    {
      if (link == lista_jogos->head_jogos)
      {
        lista_jogos->head_jogos = link->next;
      }
      else
      {
        prev->next = link->next;
      }

      if (link == lista_jogos->tail_jogos)
      {
        lista_jogos->tail_jogos = prev;
      }
      else
      {
        
      }

      free(link);
      break;
    }
    else
    {
      
    }

  }

  return;
}

void elimina_lista_ordenada(pLst_Ord lista_jogos, char *nome)
{
  link_jogo link;
  link_jogo prev;
  for (link = lista_jogos->head_jogos, prev = 0; link != 0; prev = link, link = link->next)
  {
    if (!strcmp(link->jogo->nome, nome))
    {
      if (link == lista_jogos->head_jogos)
      {
        lista_jogos->head_jogos = link->next;
      }
      else
      {
        prev->next = link->next;
      }

      if (link == lista_jogos->tail_jogos)
      {
        lista_jogos->tail_jogos = prev;
      }
      else
      {
        
      }

      free(link->jogo->equipa_1);
      free(link->jogo->equipa_2);
      free(link->jogo->nome);
      free(link->jogo);
      free(link);
      break;
    }
    else
    {
      
    }

  }

  return;
}

void adiciona_equipa(int NL, pListas *listas, pLst_Ord lista_ordenada, int m)
{
  int index;
  char nome[1023];
  link_equipa nova_equipa = (link_equipa) malloc(sizeof(struct node_equipa));
  for (int nome_index = 0; nome_index < 10; nome_index++)
  {
    nome[nome_index] = new_sym_var(sizeof(char) * 8);
  }

  nome[10 - 1] = '\0';
  index = hashU(nome, m);
  if (procura_equipa(listas, nome, m) != 0)
  {
    printf("%d Equipa existente.\n", NL);
    free(nova_equipa);
    return;
  }
  else
  {
    
  }

  nova_equipa->equipa = (pEquipa) malloc(sizeof(struct Equipa));
  nova_equipa->next = 0;
  nova_equipa->equipa->nome = str_dup(nome);
  nova_equipa->equipa->vitorias = 0;
  insere_equipa(listas[index], nova_equipa);
  lista_ordenada->lista_equipas[lista_ordenada->cont_equipas] = nova_equipa->equipa;
  lista_ordenada->cont_equipas++;
}

void adiciona_jogo(int NL, pListas *listas, pLst_Ord lista_ordenada, int m)
{
  int index;
  char nome[1023];
  char equipa_1[1023];
  char equipa_2[1023];
  int pontuacao_1;
  int pontuacao_2;
  link_equipa equipa_vencedora;
  link_jogo novo_jogo_hash = (link_jogo) malloc(sizeof(struct node_jogo));
  link_jogo novo_jogo_lista_ordenada = (link_jogo) malloc(sizeof(struct node_jogo));
  for (int nome_index = 0; nome_index < 10; nome_index++)
  {
    nome[nome_index] = new_sym_var(sizeof(char) * 8);
  }

  nome[10 - 1] = '\0';
  for (int equipa_1_index = 0; equipa_1_index < 10; equipa_1_index++)
  {
    equipa_1[equipa_1_index] = new_sym_var(sizeof(char) * 8);
  }

  equipa_1[10 - 1] = '\0';
  for (int equipa_2_index = 0; equipa_2_index < 10; equipa_2_index++)
  {
    equipa_2[equipa_2_index] = new_sym_var(sizeof(char) * 8);
  }

  equipa_2[10 - 1] = '\0';
  pontuacao_1 = new_sym_var(sizeof(int) * 8);
  pontuacao_2 = new_sym_var(sizeof(int) * 8);
  index = hashU(nome, m);
  if (procura_jogo(listas, nome, m) != 0)
  {
    printf("%d Jogo existente.\n", NL);
    free(novo_jogo_hash);
    free(novo_jogo_lista_ordenada);
    return;
  }
  else
  {
    
  }

  if ((procura_equipa(listas, equipa_1, m) == 0) || (procura_equipa(listas, equipa_2, m) == 0))
  {
    printf("%d Equipa inexistente.\n", NL);
    free(novo_jogo_hash);
    free(novo_jogo_lista_ordenada);
    return;
  }
  else
  {
    
  }

  if (pontuacao_1 > pontuacao_2)
  {
    equipa_vencedora = procura_equipa(listas, equipa_1, m);
    equipa_vencedora->equipa->vitorias++;
  }
  else
  {
    if (pontuacao_2 > pontuacao_1)
    {
      equipa_vencedora = procura_equipa(listas, equipa_2, m);
      equipa_vencedora->equipa->vitorias++;
    }
    else
    {
      
    }

  }

  novo_jogo_hash->jogo = (pJogo) malloc(sizeof(struct Jogo));
  novo_jogo_hash->next = 0;
  novo_jogo_hash->jogo->equipa_1 = str_dup(equipa_1);
  novo_jogo_hash->jogo->equipa_2 = str_dup(equipa_2);
  novo_jogo_hash->jogo->nome = str_dup(nome);
  novo_jogo_hash->jogo->pontuacao[0] = pontuacao_1;
  novo_jogo_hash->jogo->pontuacao[1] = pontuacao_2;
  novo_jogo_lista_ordenada->jogo = novo_jogo_hash->jogo;
  novo_jogo_lista_ordenada->next = 0;
  insere_jogo_hash(listas[index], novo_jogo_hash);
  insere_jogo_lista_ordenada(lista_ordenada, novo_jogo_lista_ordenada);
}

void consulta_equipa(int NL, pListas *listas, int m)
{
  char nome[1023];
  int vitorias;
  link_equipa link;
  for (int nome_index = 0; nome_index < 10; nome_index++)
  {
    nome[nome_index] = new_sym_var(sizeof(char) * 8);
  }

  nome[10 - 1] = '\0';
  link = procura_equipa(listas, nome, m);
  if (link == 0)
  {
    printf("%d Equipa inexistente.\n", NL);
    return;
  }
  else
  {
    
  }

  vitorias = link->equipa->vitorias;
  printf("%d %s %d\n", NL, nome, vitorias);
}

void consulta_jogo(int NL, pListas *listas, int m)
{
  char nome[1023];
  int pontuacao_1;
  int pontuacao_2;
  link_jogo link;
  for (int nome_index = 0; nome_index < 10; nome_index++)
  {
    nome[nome_index] = new_sym_var(sizeof(char) * 8);
  }

  nome[10 - 1] = '\0';
  link = procura_jogo(listas, nome, m);
  if (link == 0)
  {
    printf("%d Jogo inexistente.\n", NL);
    return;
  }
  else
  {
    
  }

  pontuacao_1 = link->jogo->pontuacao[0];
  pontuacao_2 = link->jogo->pontuacao[1];
  printf("%d %s %s %s %d %d\n", NL, nome, link->jogo->equipa_1, link->jogo->equipa_2, pontuacao_1, pontuacao_2);
}

void jogos_ordenados(int NL, pLst_Ord lista_ordenada)
{
  link_jogo link;
  if (lista_ordenada->head_jogos == 0)
  {
    return;
  }
  else
  {
    
  }

  for (link = lista_ordenada->head_jogos; link != 0; link = link->next)
  {
    printf("%d %s %s %s %d %d\n", NL, link->jogo->nome, link->jogo->equipa_1, link->jogo->equipa_2, link->jogo->pontuacao[0], link->jogo->pontuacao[1]);
  }

  return;
}

void remove_jogo(int NL, pListas *listas, pLst_Ord lista_ordenada, int m)
{
  char nome[1023];
  int index;
  int pontuacao_1;
  int pontuacao_2;
  link_jogo link;
  link_equipa equipa_vencedora;
  for (int nome_index = 0; nome_index < 10; nome_index++)
  {
    nome[nome_index] = new_sym_var(sizeof(char) * 8);
  }

  nome[10 - 1] = '\0';
  link = procura_jogo(listas, nome, m);
  if (link == 0)
  {
    printf("%d Jogo inexistente.\n", NL);
    return;
  }
  else
  {
    
  }

  pontuacao_1 = link->jogo->pontuacao[0];
  pontuacao_2 = link->jogo->pontuacao[1];
  if (pontuacao_1 > pontuacao_2)
  {
    equipa_vencedora = procura_equipa(listas, link->jogo->equipa_1, m);
    equipa_vencedora->equipa->vitorias--;
  }
  else
  {
    if (pontuacao_2 > pontuacao_1)
    {
      equipa_vencedora = procura_equipa(listas, link->jogo->equipa_2, m);
      equipa_vencedora->equipa->vitorias--;
    }
    else
    {
      
    }

  }

  index = hashU(nome, m);
  elimina_hash(listas[index], nome);
  elimina_lista_ordenada(lista_ordenada, nome);
  return;
}

void altera_pontuacao(int NL, pListas *listas, int m)
{
  char nome[1023];
  int pontuacao_1_nova;
  int pontuacao_2_nova;
  int pontuacao_1_antiga;
  int pontuacao_2_antiga;
  link_jogo link;
  link_equipa equipa_vencedora;
  link_equipa equipa_derrotada;
  for (int nome_index = 0; nome_index < 10; nome_index++)
  {
    nome[nome_index] = new_sym_var(sizeof(char) * 8);
  }

  nome[10 - 1] = '\0';
  pontuacao_1_nova = new_sym_var(sizeof(int) * 8);
  pontuacao_2_nova = new_sym_var(sizeof(int) * 8);
  link = procura_jogo(listas, nome, m);
  if (link == 0)
  {
    printf("%d Jogo inexistente.\n", NL);
    return;
  }
  else
  {
    
  }

  pontuacao_1_antiga = link->jogo->pontuacao[0];
  pontuacao_2_antiga = link->jogo->pontuacao[1];
  link->jogo->pontuacao[0] = pontuacao_1_nova;
  link->jogo->pontuacao[1] = pontuacao_2_nova;
  if ((pontuacao_1_antiga < pontuacao_2_antiga) && (pontuacao_1_nova == pontuacao_2_nova))
  {
    equipa_derrotada = procura_equipa(listas, link->jogo->equipa_2, m);
    equipa_derrotada->equipa->vitorias--;
  }
  else
  {
    if ((pontuacao_1_antiga < pontuacao_2_antiga) && (pontuacao_1_nova > pontuacao_2_nova))
    {
      equipa_vencedora = procura_equipa(listas, link->jogo->equipa_1, m);
      equipa_derrotada = procura_equipa(listas, link->jogo->equipa_2, m);
      equipa_vencedora->equipa->vitorias++;
      equipa_derrotada->equipa->vitorias--;
    }
    else
    {
      if ((pontuacao_1_antiga > pontuacao_2_antiga) && (pontuacao_1_nova == pontuacao_2_nova))
      {
        equipa_derrotada = procura_equipa(listas, link->jogo->equipa_1, m);
        equipa_derrotada->equipa->vitorias--;
      }
      else
      {
        if ((pontuacao_1_antiga > pontuacao_2_antiga) && (pontuacao_1_nova < pontuacao_2_nova))
        {
          equipa_vencedora = procura_equipa(listas, link->jogo->equipa_2, m);
          equipa_derrotada = procura_equipa(listas, link->jogo->equipa_1, m);
          equipa_vencedora->equipa->vitorias++;
          equipa_derrotada->equipa->vitorias--;
        }
        else
        {
          if ((pontuacao_1_antiga == pontuacao_2_antiga) && (pontuacao_1_nova < pontuacao_2_nova))
          {
            equipa_vencedora = procura_equipa(listas, link->jogo->equipa_2, m);
            equipa_vencedora->equipa->vitorias++;
          }
          else
          {
            if ((pontuacao_1_antiga == pontuacao_2_antiga) && (pontuacao_1_nova > pontuacao_2_nova))
            {
              equipa_vencedora = procura_equipa(listas, link->jogo->equipa_1, m);
              equipa_vencedora->equipa->vitorias++;
            }
            else
            {
              
            }

          }

        }

      }

    }

  }

  return;
}

int compara_vitorias(const void *a, const void *b)
{
  pEquipa *l = (pEquipa *) a;
  pEquipa *r = (pEquipa *) b;
  return (*r)->vitorias - (*l)->vitorias;
}

int compara_nomes(const void *a, const void *b)
{
  pEquipa *l = (pEquipa *) a;
  pEquipa *r = (pEquipa *) b;
  return strcmp((*l)->nome, (*r)->nome);
}

void ordena_equipas_vitorias(int NL, pLst_Ord lista_ordenada)
{
  int i;
  int max_vitorias;
  int max_equipas_vencedoras = 0;
  pEquipa *equipas_vencedoras = (pEquipa *) malloc((sizeof(pEquipa)) * lista_ordenada->cont_equipas);
  if (!lista_ordenada->cont_equipas)
  {
    free(equipas_vencedoras);
    return;
  }
  else
  {
    
  }

  qsort(lista_ordenada->lista_equipas, lista_ordenada->cont_equipas, sizeof(pEquipa), compara_vitorias);
  max_vitorias = lista_ordenada->lista_equipas[0]->vitorias;
  for (i = 0; (i < lista_ordenada->cont_equipas) && (lista_ordenada->lista_equipas[i]->vitorias == max_vitorias); i++)
  {
    equipas_vencedoras[i] = lista_ordenada->lista_equipas[i];
    max_equipas_vencedoras++;
  }

  equipas_vencedoras = (pEquipa *) realloc(equipas_vencedoras, (sizeof(pEquipa)) * max_equipas_vencedoras);
  qsort(equipas_vencedoras, max_equipas_vencedoras, sizeof(pEquipa), compara_nomes);
  printf("%d Melhores %d\n", NL, max_vitorias);
  for (i = 0; i < max_equipas_vencedoras; i++)
  {
    printf("%d * %s\n", NL, equipas_vencedoras[i]->nome);
  }

  free(equipas_vencedoras);
  return;
}

void free_equipas(link_equipa head_equipas)
{
  link_equipa link;
  link_equipa aux;
  link = head_equipas;
  while (link != 0)
  {
    free(link->equipa->nome);
    free(link->equipa);
    aux = link;
    link = link->next;
    free(aux);
  }

  return;
}

void free_jogos(link_jogo head_jogos, int flag_struct)
{
  link_jogo link;
  link_jogo aux;
  link = head_jogos;
  while (link != 0)
  {
    if (flag_struct == 0)
    {
      free(link->jogo->nome);
      free(link->jogo->equipa_1);
      free(link->jogo->equipa_2);
      free(link->jogo);
    }
    else
    {
      
    }

    aux = link;
    link = link->next;
    free(aux);
  }

  return;
}

void free_listas(pListas *listas, int m)
{
  int i;
  for (i = 0; i < m; i++)
  {
    free_equipas(listas[i]->head_equipas);
    free_jogos(listas[i]->head_jogos, 1);
    free(listas[i]);
  }

  free(listas);
  return;
}

void free_lista_ordenada(pLst_Ord lista_ordenada)
{
  free(lista_ordenada->lista_equipas);
  free_jogos(lista_ordenada->head_jogos, 0);
  free(lista_ordenada);
  return;
}

