/*File generated by PreProcessor.py*/


#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "comandos.h"
#include "lista.h"
#include "hash_table_equipa.h"
#include "hash_table_jogo.h"


int main(void)
{
  jogo *hash_table_jogo[2000];
  equipa *hash_table_equipa[2000];
  node *head;
  equipa *aux_equipa;
  jogo *aux_jogo;
  node *aux_node;
  char Comando = LeCaracterInicial();
  int contador;
  contador = 1;
  init_hash_table_equipa(hash_table_equipa);
  init_hash_table_jogo(hash_table_jogo);
  head = 0;
  while (Comando != 'x')
  {
    switch (Comando)
    {
      case 'a':
        aux_jogo = Comando_a(contador, hash_table_equipa, hash_table_jogo);
        if (aux_jogo != 0)
      {
        {
          hash_table_jogo_insert(aux_jogo, hash_table_jogo);
          aux_node = lista_insert(aux_jogo, head);
          head = aux_node;
        }
      }
      else
      {
        
      }

        contador++;
        break;

      case 'A':
        aux_equipa = Comando_A(contador, hash_table_equipa);
        if (aux_equipa != 0)
      {
        {
          aux_equipa->vitorias = 0;
          hash_table_equipa_insert(aux_equipa, hash_table_equipa);
        }
      }
      else
      {
        
      }

        contador++;
        break;

      case 'l':
        contador = Comando_l(contador, head);
        contador++;
        break;

      case 'p':
        Comando_p(contador, hash_table_jogo);
        contador++;
        break;

      case 'P':
        Comando_P(contador, hash_table_equipa);
        contador++;
        break;

      case 'r':
        aux_jogo = Comando_r(contador, hash_table_jogo, hash_table_equipa);
        if (aux_jogo != 0)
      {
        {
          hash_table_jogo_delete(aux_jogo->nome_jogo, hash_table_jogo);
          aux_node = lista_delete(aux_jogo->nome_jogo, head);
          head = aux_node;
        }
      }
      else
      {
        
      }

        contador++;
        break;

      case 's':
        aux_node = Comando_s(contador, hash_table_jogo, hash_table_equipa, head);
        head = aux_node;
        contador++;
        break;

      case 'g':
        contador = Comando_g(contador, hash_table_equipa);
        contador++;
        break;

      default:
        break;

    }

    Comando = LeCaracterInicial();
  }

  free_equipas(hash_table_equipa);
  free_jogos(hash_table_jogo);
  free_listas(head);
  return 0;
}

