/*File generated by PreProcessor.py*/


#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "equipas.h"
#include "hash_equipas.h"


char *strdup(const char *src)
{
  char *dst = malloc((strlen(src) + 1) * (sizeof(char)));
  if (dst == 0)
  {
    return 0;
  }
  else
  {
    
  }

  strcpy(dst, src);
  return dst;
}

void free_equipa(equipa x)
{
  free(x->nome_equipa);
  free(x);
}

equipa cria_equipa(char *nome)
{
  equipa nova = (equipa) malloc(sizeof(struct equipa));
  nova->nome_equipa = strdup(nome);
  nova->vitorias = 0;
  return nova;
}

void adiciona_equipa(int nl, equipa *ht)
{
  char *nome = malloc(1023 * (sizeof(char)));
  int verif;
  equipa nova;
  for (int nome_index = 0; nome_index < 10; nome_index++)
  {
    nome[nome_index] = new_sym_var(sizeof(char) * 8);
  }

  nome[10 - 1] = '\0';
  nova = cria_equipa(nome);
  verif = procura_equipa(nova->nome_equipa, ht);
  if (verif >= 0)
  {
    printf("%d Equipa existente.\n", nl);
    free_equipa(nova);
  }
  else
  {
    tab_insert_eq(nova, ht);
  }

  free(nome);
}

void encontra_equipa(int nl, equipa *ht)
{
  char *nome = malloc(1023 * (sizeof(char)));
  int indice;
  for (int nome_index = 0; nome_index < 10; nome_index++)
  {
    nome[nome_index] = new_sym_var(sizeof(char) * 8);
  }

  nome[10 - 1] = '\0';
  indice = procura_equipa(nome, ht);
  if (indice == (-1))
  {
    printf("%d Equipa inexistente.\n", nl);
  }
  else
  {
    printf("%d %s %d\n", nl, ht[indice]->nome_equipa, ht[indice]->vitorias);
  }

  free(nome);
}

int compara_palavras(const void *a, const void *b)
{
  const char **str1 = (const char **) a;
  const char **str2 = (const char **) b;
  return strcmp(*str1, *str2);
}

void melhores_equipas(int nl, equipa *ht)
{
  int best = 0;
  int contador = 0;
  int i;
  int indice = 0;
  char **nomes;
  for (i = 0; i < 32911; i++)
  {
    if (ht[i] != 0)
    {
      if (ht[i]->vitorias > best)
      {
        best = ht[i]->vitorias;
        contador = 1;
      }
      else
      {
        if (ht[i]->vitorias == best)
        {
          contador += 1;
        }
        else
        {
          
        }

      }

    }
    else
    {
      
    }

  }

  if (contador > 0)
  {
    nomes = malloc(contador * (sizeof(char *)));
    for (i = 0; i < 32911; i++)
    {
      if (ht[i] != 0)
      {
        if (ht[i]->vitorias == best)
        {
          nomes[indice] = ht[i]->nome_equipa;
          indice += 1;
        }
        else
        {
          
        }

      }
      else
      {
        
      }

    }

    qsort(nomes, contador, sizeof(char *), compara_palavras);
    printf("%d Melhores %d\n", nl, best);
    for (i = 0; i < contador; i++)
    {
      printf("%d * %s\n", nl, nomes[i]);
    }

    free(nomes);
  }
  else
  {
    
  }

}

