#include "/home/fmarques/sbugs/projects/alunos/lib/stubs.h"
/*File generated by PreProcessor.py*/


#include "lista.h"


Node_team *insert_begin(Node_team *head, char *nome)
{
  Node_team *new = malloc(sizeof(Node_team));
  new->nome = malloc((sizeof(char)) * (strlen(nome) + 1));
  strcpy(new->nome, nome);
  new->vitorias = 0;
  new->next = head;
  return new;
}

Node_team *search_team(Node_team *head, char *nome)
{
  for (; head != 0; head = head->next)
  {
    if (strcmp(head->nome, nome) == 0)
    {
      return head;
    }
    else
    {
      
    }

  }

  return 0;
}

void free_node_team(Node_team *node)
{
  free(node->nome);
  free(node);
}

Node_team *clear_node_team(Node_team *head)
{
  Node_team *aux;
  while (head)
  {
    aux = head->next;
    free_node_team(head);
    head = aux;
  }

  return 0;
}

Node_game *insert_end(Node_game_lst *Lst_jogos, char *nome_jogo, char *equipa1, char *equipa2, int golos_equipa1, int golos_equipa2)
{
  Node_game *new = malloc(sizeof(Node_game));
  new->jogo = malloc(sizeof(Jogo));
  new->jogo->nome = malloc((sizeof(char)) * (strlen(nome_jogo) + 1));
  strcpy(new->jogo->nome, nome_jogo);
  new->jogo->equipa1 = malloc((sizeof(char)) * (strlen(equipa1) + 1));
  strcpy(new->jogo->equipa1, equipa1);
  new->jogo->equipa2 = malloc((sizeof(char)) * (strlen(equipa2) + 1));
  strcpy(new->jogo->equipa2, equipa2);
  new->jogo->golos_equipa1 = golos_equipa1;
  new->jogo->golos_equipa2 = golos_equipa2;
  new->next = 0;
  if (Lst_jogos->head == 0)
  {
    new->prev = 0;
    Lst_jogos->head = new;
  }
  else
  {
    Lst_jogos->last->next = new;
    new->prev = Lst_jogos->last;
  }

  Lst_jogos->last = new;
  return Lst_jogos->head;
}

void clear_node_game(Node_game *node)
{
  free(node->jogo->nome);
  free(node->jogo->equipa1);
  free(node->jogo->equipa2);
  free(node->jogo);
  free(node);
}

Node_game *clear_lst_node_game(Node_game *head)
{
  Node_game *aux;
  while (head)
  {
    aux = head->next;
    clear_node_game(head);
    head = aux;
  }

  return 0;
}

Node_game_lst *init_node_game_lst()
{
  Node_game_lst *Lst_jogos = malloc(sizeof(Node_game_lst));
  Lst_jogos->head = 0;
  Lst_jogos->last = 0;
  return Lst_jogos;
}

void clear_node_game_lst(Node_game_lst *Lst_jogos)
{
  clear_lst_node_game(Lst_jogos->head);
  free(Lst_jogos);
}

Node_g_ht *insert_begin_games(Node_g_ht *head, Node_game *node_game_ptr)
{
  Node_g_ht *new = malloc(sizeof(Node_g_ht));
  new->node_game_ptr = node_game_ptr;
  new->next = head;
  new->prev = 0;
  if (head != 0)
  {
    head->prev = new;
  }
  else
  {
    
  }

  return new;
}

Node_g_ht *search_game_lst(Node_g_ht *head, char *nome)
{
  for (; head != 0; head = head->next)
  {
    if (strcmp(head->node_game_ptr->jogo->nome, nome) == 0)
    {
      return head;
    }
    else
    {
      
    }

  }

  return 0;
}

void clear_node_g_ht(Node_g_ht *node)
{
  free(node);
}

Node_g_ht *clear_lst_node_g_ht(Node_g_ht *head)
{
  Node_g_ht *aux;
  while (head)
  {
    aux = head->next;
    clear_node_g_ht(head);
    head = aux;
  }

  return 0;
}

