#include "/home/fmarques/sbugs/projects/alunos/lib/stubs.h"
/*File generated by PreProcessor.py*/


#include "teams.h"


void add_team(Hash_table HT, int line)
{
  char nome[1023];
  for (int nome_index = 0; nome_index < 10; nome_index++)
  {
    nome[nome_index] = new_sym_var(sizeof(char) * 8);
  }

  nome[10 - 1] = '\0';
  if (!search_HT(HT, nome))
  {
    HT_insert(HT, nome);
  }
  else
  {
    printf("%d Equipa existente.\n", line);
  }

}

void search_team_name(Hash_table HT, int line)
{
  char nome[1023];
  Node_team *p;
  for (int nome_index = 0; nome_index < 10; nome_index++)
  {
    nome[nome_index] = new_sym_var(sizeof(char) * 8);
  }

  nome[10 - 1] = '\0';
  p = search_HT(HT, nome);
  if (!p)
  {
    printf("%d Equipa inexistente.\n", line);
  }
  else
  {
    printf("%d %s %d\n", line, p->nome, p->vitorias);
  }

}

void print_most_wins(Hash_table HT, int line)
{
  int most_wins = search_most_wins(HT);
  int i;
  int last;
  Node_team *array_teams[100];
  for (i = 0; i < 100; i++)
  {
    array_teams[i] = 0;
  }

  last = create_teams_array(HT, array_teams, most_wins);
  if (array_teams[0] != 0)
  {
    if (last > 0)
    {
      merge_sort(array_teams, 0, last - 1);
    }
    else
    {
      
    }

    printf("%d Melhores %d\n", line, most_wins);
    for (i = 0; i < last; i++)
    {
      printf("%d * %s\n", line, array_teams[i]->nome);
    }

  }
  else
  {
    
  }

}

int search_most_wins(Hash_table HT)
{
  int most_wins = 0;
  int i;
  Node_team *aux;
  for (i = 0; i < 1777; i++)
  {
    aux = HT.heads[i];
    for (; aux != 0; aux = aux->next)
    {
      if (aux->vitorias > most_wins)
      {
        most_wins = aux->vitorias;
      }
      else
      {
        
      }

    }

  }

  return most_wins;
}

int create_teams_array(Hash_table HT, Node_team **head, int most_wins)
{
  int i;
  int u = 0;
  Node_team *aux;
  for (i = 0; i < 1777; i++)
  {
    aux = HT.heads[i];
    for (; aux != 0; aux = aux->next)
    {
      if (aux->vitorias == most_wins)
      {
        head[u++] = aux;
      }
      else
      {
        
      }

    }

  }

  return u;
}

void merge_sort(Node_team **array_teams, int left, int right)
{
  int mid = (left + right) / 2;
  if (right <= left)
  {
    return;
  }
  else
  {
    merge_sort(array_teams, left, mid);
    merge_sort(array_teams, mid + 1, right);
    merge(array_teams, left, mid, right);
  }

}

void merge(Node_team **array_teams, int left, int mid, int right)
{
  int i;
  int j;
  int k;
  Node_team *array_teams_aux[100];
  for (i = 0; i < 100; i++)
  {
    array_teams_aux[i] = 0;
  }

  for (i = mid + 1; i > left; i--)
  {
    array_teams_aux[i - 1] = array_teams[i - 1];
  }

  for (j = mid; j < right; j++)
  {
    array_teams_aux[(right + mid) - j] = array_teams[j + 1];
  }

  for (k = left; k <= right; k++)
  {
    if (strcmp(array_teams_aux[j]->nome, array_teams_aux[i]->nome) < 0)
    {
      array_teams[k] = array_teams_aux[j--];
    }
    else
    {
      array_teams[k] = array_teams_aux[i++];
    }

  }

}

