#include "/home/fmarques/sbugs/projects/alunos/lib/stubs.h"
/*File generated by PreProcessor.py*/


#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "custom_types.h"
#include "game_linked_list.h"
#include "game_hash_table.h"


int gameHash(char *str, int m)
{
  int i;
  int dim;
  int len = strlen(str);
  int res = 0;
  dim = (len > 20) ? (20) : (len);
  for (i = 0; i < dim; i++)
    res += str[i] * (i + 1);

  return res % m;
}

char *gameKey(GameLink link)
{
  return link->game->name;
}

GameHT_node gameHtNodeInsert(GameHT_node head, GameLink link)
{
  GameHT_node newnode = malloc(sizeof(struct stru_ht_node));
  newnode->link = link;
  newnode->next = head;
  return newnode;
}

GameHT_node gameHtNodeSelect(GameHT_node head, char *name)
{
  for (; head; head = head->next)
    if (!strcmp(gameKey(head->link), name))
  {
    return head;
  }
  else
  {
    
  }


  return 0;
}

GameHT_node gameHtNodeRemove(GameHT_node head, char *name)
{
  GameHT_node previous;
  GameHT_node temp;
  for (previous = 0, temp = head; temp; previous = temp, temp = temp->next)
    if (!strcmp(gameKey(temp->link), name))
  {
    if (previous)
    {
      previous->next = temp->next;
    }
    else
    {
      head = temp->next;
    }

    free(temp);
    break;
  }
  else
  {
    
  }


  return head;
}

GameHtable gameHtInit(int dim)
{
  int i;
  GameHtable table = malloc(dim * (sizeof(struct stru_ht_node)));
  for (i = 0; i < dim; i++)
    table[i] = 0;

  return table;
}

void gameHtIndexRemove(GameHT_node head)
{
  GameHT_node temp;
  while (head)
  {
    temp = head;
    head = head->next;
    free(temp);
  }

}

void gameHtFree(GameHtable table, int dim)
{
  int i;
  for (i = 0; i < dim; i++)
    (table[i]) ? (gameHtIndexRemove(table[i])) : (free(table[i]));

  free(table);
}

