/*File generated by PreProcessor.py*/


#include "team.h"


Team *newTeam(char *name, int wins)
{
  Team *team = (Team *) malloc(sizeof(Team));
  team->name = (char *) malloc((sizeof(char)) * (strlen(name) + 1));
  strcpy(team->name, name);
  team->wins = wins;
  return team;
}

void freeTeam(Team *team)
{
  free(team->name);
  free(team);
}

char *getTeamName(Team *team)
{
  return team->name;
}

int getTeamWins(Team *team)
{
  return team->wins;
}

void addTeamWins(Team *team, int wins)
{
  team->wins = team->wins + wins;
}

void printTeam(Team *team, int nl)
{
  printf("%d * %s\n", nl, team->name);
}

int teamKeyOrder(char *name, Team *team)
{
  return strcmp(name, team->name);
}

int teamsOrder(Team *team1, Team *team2)
{
  return strcmp(team1->name, team2->name);
}

