/*File generated by PreProcessor.py*/


#include "hash.h"


int hash(char *key, int size)
{
  int hash = 0;
  int a = 127;
  for (; (*key) != '\0'; key++)
    hash = ((a * hash) + (*key)) % size;

  return hash;
}

Hashtable *htInit()
{
  Hashtable *ht;
  int i;
  ht = malloc(sizeof(Hashtable));
  ht->list = (List **) malloc(1999 * (sizeof(List)));
  for (i = 0; i < 1999; i++)
    ht->list[i] = 0;

  return ht;
}

void createNode(Hashtable *ht, char id)
{
  List *linkNode;
  linkNode = malloc(sizeof(List));
  switch (id)
  {
    case 'g':
      createNewGame(linkNode);
      break;

    case 't':
      createNewTeam(linkNode);
      break;

  }

  linkNode->next = 0;
  insertNode(ht, linkNode, id);
}

void insertNode(Hashtable *ht, List *linkNode, char id)
{
  int ind;
  switch (id)
  {
    case 'g':
      ind = hash(((Game *) linkNode->data)->name, 1999);
      break;

    case 't':
      ind = hash(((Team *) linkNode->data)->name, 1999);
      break;

  }

  if (ht->list[ind] == 0)
  {
    {
      linkNode->next = 0;
      ht->list[ind] = linkNode;
    }
  }
  else
  {
    {
      linkNode->next = ht->list[ind];
      ht->list[ind] = linkNode;
    }
  }

}

List *searchNode(Hashtable *ht, char *name, char id)
{
  List *node;
  char *nameP;
  int ind;
  nameP = name;
  ind = hash(nameP, 1999);
  node = ht->list[ind];
  switch (id)
  {
    case 'g':
      while (node != 0)
    {
      if (strcmp(((Game *) node->data)->name, name) == 0)
      {
        break;
      }
      else
      {
        
      }

      node = node->next;
    }

      break;

    case 't':
      while (node != 0)
    {
      if (strcmp(((Team *) node->data)->name, name) == 0)
      {
        break;
      }
      else
      {
        
      }

      node = node->next;
    }

      break;

  }

  return node;
}

void removeGameNode(Game *gameNode)
{
  List *list;
  List *temp;
  List *previousNode;
  Game *tempInfo;
  int ind = hash(gameNode->name, 1999);
  removeGamesWon(gameNode);
  removeListGames(gameNode);
  list = htGames->list[ind];
  previousNode = list;
  while (list != 0)
  {
    temp = list;
    tempInfo = (Game *) temp->data;
    if (strcmp(tempInfo->name, gameNode->name) == 0)
    {
      {
        previousNode->next = temp->next;
        freeData(tempInfo, 'g');
        free(temp->data);
        temp->data = 0;
        if (previousNode == temp)
        {
          {
            htGames->list[ind] = temp->next;
          }
        }
        else
        {
          
        }

        free(temp);
        temp = 0;
        return;
      }
    }
    else
    {
      {
        previousNode = list;
        list = list->next;
      }
    }

  }

}

void htFree(Hashtable *ht, char id)
{
  int i;
  List *temp;
  List *linkedList;
  for (i = 0; i < 1999; i++)
  {
    linkedList = ht->list[i];
    while (linkedList != 0)
    {
      temp = linkedList->next;
      freeData(linkedList->data, id);
      free(linkedList->data);
      linkedList->data = 0;
      free(linkedList);
      linkedList = temp;
    }

    free(linkedList);
    linkedList = 0;
  }

  free(ht->list);
  ht->list = 0;
  free(ht);
  ht = 0;
}

void freeData(void *data, char id)
{
  switch (id)
  {
    case 'g':
      free(((Game *) data)->name);
      free(((Game *) data)->team1);
      free(((Game *) data)->team2);
      break;

    case 't':
      free(((Team *) data)->name);
      break;

  }

}

