#include "/home/fmarques/sbugs/projects/alunos/lib/stubs.h"
/*File generated by PreProcessor.py*/


#include <stdio.h>
#include <string.h>


typedef struct produtos
{
  int idp;
  char descricao[64];
  int preco;
  int peso;
  int qtd;
} produtos;
typedef struct encomenda_l
{
  produtos l2_produtos[200];
  int peso;
  int ide;
  int n_produtos;
} encomenda_l;
void f_produto();
void listar_produtos();
void add_stock();
void add_encomenda();
void add_produto_enc();
void remove_stock();
void remove_produto();
void custo_encomenda();
void altera_preco();
void descricao_qtd();
void max_produto();
void listar_prod_encomenda();
void listar_preco();
void listar_preco_aux();
void comando_l();
void comando_L();
void insertion();
produtos produto[10000];
encomenda_l encomenda[500];
int idp = 0;
int ide = 0;
int main()
{
  char ch_main;
  while (ch_main != 'x')
  {
    switch (ch_main = getchar())
    {
      case 'a':
        f_produto();
        break;

      case 'k':
        listar_produtos();
        break;

      case 'q':
        add_stock();
        break;

      case 'N':
        add_encomenda();
        break;

      case 'A':
        add_produto_enc();
        break;

      case 'r':
        remove_stock();
        break;

      case 'R':
        remove_produto();
        break;

      case 'C':
        custo_encomenda();
        break;

      case 'p':
        altera_preco();
        break;

      case 'E':
        descricao_qtd();
        break;

      case 'm':
        max_produto();
        break;

      case 'K':
        listar_prod_encomenda();
        break;

      case 'l':
        comando_l();
        break;

      case 'L':
        comando_L();
        break;

    }

  }

  return 0;
}

void f_produto()
{
  for (int produto_index = 0; produto_index < 10; produto_index++)
  {
    produto[idp].descricao[produto_index] = new_sym_var(sizeof(char) * 8);
  }

  produto[idp].descricao[10 - 1] = '\0';
  produto[idp].preco = new_sym_var(sizeof(int) * 8);
  produto[idp].peso = new_sym_var(sizeof(int) * 8);
  produto[idp].qtd = new_sym_var(sizeof(int) * 8);
  printf("Novo produto %d.\n", idp);
  produto[idp].idp = idp;
  idp++;
}

void listar_produtos()
{
  int i;
  for (i = 0; i < idp; i++)
  {
    printf("%s:%d:%d:%d\n", produto[i].descricao, produto[i].preco, produto[i].peso, produto[i].qtd);
  }

}

void add_stock()
{
  int id1;
  int qtd;
  id1 = new_sym_var(sizeof(int) * 8);
  qtd = new_sym_var(sizeof(int) * 8);
  if (id1 >= idp)
  {
    printf("Impossivel adicionar produto %d ao stock. Produto inexistente.\n", id1);
  }
  else
  {
    produto[id1].qtd += qtd;
  }

}

void add_encomenda()
{
  printf("Nova encomenda %d.\n", ide);
  encomenda[ide].ide = ide;
  encomenda[ide].n_produtos = 0;
  encomenda[ide].peso = 0;
  ide++;
}

void add_produto_enc()
{
  int d;
  int id1;
  int id2;
  int qtd;
  int nmr;
  int peso;
  int estado;
  estado = 1;
  id2 = new_sym_var(sizeof(int) * 8);
  id1 = new_sym_var(sizeof(int) * 8);
  qtd = new_sym_var(sizeof(int) * 8);
  if (id2 >= ide)
  {
    printf("Impossivel adicionar produto %d a encomenda %d. Encomenda inexistente.\n", id1, id2);
    return;
  }
  else
  {
    
  }

  if (id1 >= idp)
  {
    printf("Impossivel adicionar produto %d a encomenda %d. Produto inexistente.\n", id1, id2);
    return;
  }
  else
  {
    
  }

  if (qtd > produto[id1].qtd)
  {
    printf("Impossivel adicionar produto %d a encomenda %d. Quantidade em stock insuficiente.\n", id1, id2);
    return;
  }
  else
  {
    
  }

  peso = encomenda[id2].peso + (produto[id1].peso * qtd);
  if (peso > 200)
  {
    printf("Impossivel adicionar produto %d a encomenda %d. Peso da encomenda excede o maximo de 200.\n", id1, id2);
    return;
  }
  else
  {
    
  }

  nmr = encomenda[id2].n_produtos;
  for (d = 0; d < nmr; d++)
  {
    if (encomenda[id2].l2_produtos[d].idp == id1)
    {
      encomenda[id2].peso += produto[id1].peso * qtd;
      encomenda[id2].l2_produtos[d].qtd += qtd;
      produto[id1].qtd -= qtd;
      estado = 0;
    }
    else
    {
      
    }

  }

  if (estado == 1)
  {
    strcpy(encomenda[id2].l2_produtos[nmr].descricao, produto[id1].descricao);
    encomenda[id2].peso += produto[id1].peso * qtd;
    encomenda[id2].l2_produtos[nmr].qtd = qtd;
    produto[id1].qtd -= qtd;
    encomenda[id2].n_produtos += 1;
    encomenda[id2].l2_produtos[nmr].idp = id1;
    encomenda[id2].l2_produtos[nmr].preco = produto[id1].preco;
    estado = 0;
  }
  else
  {
    
  }

}

void remove_stock()
{
  int id1;
  int qtd;
  id1 = new_sym_var(sizeof(int) * 8);
  qtd = new_sym_var(sizeof(int) * 8);
  if (id1 >= idp)
  {
    printf("Impossivel remover stock do produto %d. Produto inexistente.\n", id1);
    return;
  }
  else
  {
    
  }

  if (qtd > produto[id1].qtd)
  {
    printf("Impossivel remover %d unidades do produto %d do stock. Quantidade insuficiente.\n", qtd, id1);
    return;
  }
  else
  {
    produto[id1].qtd -= qtd;
  }

}

void remove_produto()
{
  int id1;
  int id2;
  int d;
  int nmr;
  id2 = new_sym_var(sizeof(int) * 8);
  id1 = new_sym_var(sizeof(int) * 8);
  if (id2 >= ide)
  {
    printf("Impossivel remover produto %d a encomenda %d. Encomenda inexistente.\n", id1, id2);
    return;
  }
  else
  {
    
  }

  if (id1 >= idp)
  {
    printf("Impossivel remover produto %d a encomenda %d. Produto inexistente.\n", id1, id2);
    return;
  }
  else
  {
    
  }

  nmr = encomenda[id2].n_produtos;
  for (d = 0; d < nmr; d++)
  {
    if (encomenda[id2].l2_produtos[d].idp == id1)
    {
      if ((nmr == 1) || (d == (nmr - 1)))
      {
        produto[id1].qtd += encomenda[id2].l2_produtos[d].qtd;
        encomenda[id2].peso -= encomenda[id2].l2_produtos[d].qtd * produto[id1].peso;
        strcpy(encomenda[id2].l2_produtos[d].descricao, "");
        encomenda[id2].l2_produtos[d].qtd = 0;
        encomenda[id2].l2_produtos[d].idp = -1;
        encomenda[id2].l2_produtos[d].preco = 0;
        encomenda[id2].l2_produtos[d].peso = 0;
        encomenda[id2].n_produtos -= 1;
        return;
      }
      else
      {
        produto[id1].qtd += encomenda[id2].l2_produtos[d].qtd;
        encomenda[id2].peso -= encomenda[id2].l2_produtos[d].qtd * produto[id1].peso;
        strcpy(encomenda[id2].l2_produtos[d].descricao, encomenda[id2].l2_produtos[nmr - 1].descricao);
        encomenda[id2].l2_produtos[d].qtd = encomenda[id2].l2_produtos[nmr - 1].qtd;
        encomenda[id2].l2_produtos[d].idp = encomenda[id2].l2_produtos[nmr - 1].idp;
        encomenda[id2].l2_produtos[d].preco = encomenda[id2].l2_produtos[nmr - 1].preco;
        encomenda[id2].l2_produtos[d].peso = encomenda[id2].l2_produtos[nmr - 1].peso;
        encomenda[id2].n_produtos -= 1;
        return;
      }

    }
    else
    {
      
    }

  }

}

void custo_encomenda()
{
  int id2;
  int d;
  int nmr;
  int total = 0;
  id2 = new_sym_var(sizeof(int) * 8);
  if (id2 >= ide)
  {
    printf("Impossivel calcular custo da encomenda %d. Encomenda inexistente.\n", id2);
    return;
  }
  else
  {
    nmr = encomenda[id2].n_produtos;
    for (d = 0; d < nmr; d++)
    {
      total += encomenda[id2].l2_produtos[d].preco * encomenda[id2].l2_produtos[d].qtd;
    }

    printf("Custo da encomenda %d %d.\n", id2, total);
  }

}

void altera_preco()
{
  int id1;
  int preco;
  int i;
  int d;
  int nmr;
  id1 = new_sym_var(sizeof(int) * 8);
  preco = new_sym_var(sizeof(int) * 8);
  if (id1 >= idp)
  {
    printf("Impossivel alterar preco do produto %d. Produto inexistente.\n", id1);
    return;
  }
  else
  {
    produto[id1].preco = preco;
    for (i = 0; i < ide; i++)
    {
      nmr = encomenda[i].n_produtos;
      for (d = 0; d < nmr; d++)
      {
        if (encomenda[i].l2_produtos[d].idp == id1)
        {
          encomenda[i].l2_produtos[d].preco = preco;
        }
        else
        {
          
        }

      }

    }

  }

}

void descricao_qtd()
{
  int id1;
  int id2;
  int d;
  int nmr;
  int estado;
  estado = 1;
  id2 = new_sym_var(sizeof(int) * 8);
  id1 = new_sym_var(sizeof(int) * 8);
  if (id2 >= ide)
  {
    printf("Impossivel listar encomenda %d. Encomenda inexistente.\n", id2);
    return;
  }
  else
  {
    
  }

  if (id1 >= idp)
  {
    printf("Impossivel listar produto %d. Produto inexistente.\n", id1);
    return;
  }
  else
  {
    
  }

  nmr = encomenda[id2].n_produtos;
  for (d = 0; d < nmr; d++)
  {
    if (encomenda[id2].l2_produtos[d].idp == id1)
    {
      printf("%s %d.\n", encomenda[id2].l2_produtos[d].descricao, encomenda[id2].l2_produtos[d].qtd);
      estado = 0;
    }
    else
    {
      
    }

  }

  if (estado == 1)
  {
    printf("%s 0.\n", produto[id1].descricao);
    return;
  }
  else
  {
    
  }

}

void max_produto()
{
  int id1;
  int i;
  int d;
  int id2;
  int estado;
  int nmr;
  int max = -1;
  estado = 0;
  id1 = new_sym_var(sizeof(int) * 8);
  if (id1 >= idp)
  {
    printf("Impossivel listar maximo do produto %d. Produto inexistente.\n", id1);
    return;
  }
  else
  {
    
  }

  for (i = 0; i < ide; i++)
  {
    nmr = encomenda[i].n_produtos;
    for (d = 0; d < nmr; d++)
    {
      if (encomenda[i].l2_produtos[d].idp == id1)
      {
        if (encomenda[i].l2_produtos[d].qtd > max)
        {
          max = encomenda[i].l2_produtos[d].qtd;
          id2 = i;
          estado = 1;
        }
        else
        {
          
        }

      }
      else
      {
        
      }

    }

  }

  if (estado == 1)
  {
    printf("Maximo produto %d %d %d.\n", id1, id2, max);
  }
  else
  {
    
  }

}

void listar_prod_encomenda()
{
  int id2;
  int d;
  int nmr;
  id2 = new_sym_var(sizeof(int) * 8);
  nmr = encomenda[id2].n_produtos;
  for (d = 0; d < nmr; d++)
  {
    printf("%s:%d\n", encomenda[id2].l2_produtos[d].descricao, encomenda[id2].l2_produtos[d].qtd);
  }

}

void listar_preco(int vetor[], int vetor2[], int left, int right)
{
  if (left < right)
  {
    int m = left + ((right - left) / 2);
    listar_preco(vetor, vetor2, left, m);
    listar_preco(vetor, vetor2, m + 1, right);
    listar_preco_aux(vetor, vetor2, left, m, right);
  }
  else
  {
    
  }

}

void listar_preco_aux(int vetor[], int vetor2[], int left, int m, int right)
{
  int i;
  int j;
  int k;
  int n1 = (m - left) + 1;
  int n2 = right - m;
  int L[10000];
  int L2[10000];
  int R[10000];
  int R2[10000];
  for (i = 0; i < n1; i++)
  {
    L[i] = vetor[left + i];
    L2[i] = vetor2[left + i];
  }

  for (j = 0; j < n2; j++)
  {
    R[j] = vetor[(m + 1) + j];
    R2[j] = vetor2[(m + 1) + j];
  }

  i = 0;
  j = 0;
  k = left;
  while ((i < n1) && (j < n2))
  {
    if (L[i] <= R[j])
    {
      vetor[k] = L[i];
      vetor2[k] = L2[i];
      i++;
    }
    else
    {
      vetor[k] = R[j];
      vetor2[k] = R2[j];
      j++;
    }

    k++;
  }

  while (i < n1)
  {
    vetor[k] = L[i];
    vetor2[k] = L2[i];
    i++;
    k++;
  }

  while (j < n2)
  {
    vetor[k] = R[j];
    vetor2[k] = R2[j];
    j++;
    k++;
  }

}

void comando_l()
{
  int i;
  int precos[10000];
  int idps[10000];
  for (i = 0; i < idp; i++)
  {
    precos[i] = produto[i].preco;
    idps[i] = produto[i].idp;
  }

  listar_preco(precos, idps, 0, idp - 1);
  printf("Produtos\n");
  for (i = 0; i < idp; i++)
  {
    printf("* %s %d %d\n", produto[idps[i]].descricao, produto[idps[i]].preco, produto[idps[i]].qtd);
  }

}

void comando_L()
{
  int id2;
  int nmr;
  char nomes[200][64];
  int indices[200];
  int i;
  int n;
  id2 = new_sym_var(sizeof(int) * 8);
  if (id2 >= ide)
  {
    printf("Impossivel listar encomenda %d. Encomenda inexistente.\n", id2);
    return;
  }
  else
  {
    
  }

  nmr = encomenda[id2].n_produtos;
  for (i = 0; i < nmr; i++)
  {
    strcpy(nomes[i], encomenda[id2].l2_produtos[i].descricao);
    indices[i] = i;
  }

  insertion(nomes, indices, nmr);
  printf("Encomenda %d\n", id2);
  for (i = 0; i < nmr; i++)
  {
    n = indices[i];
    printf("* %s %d %d\n", nomes[i], encomenda[id2].l2_produtos[n].preco, encomenda[id2].l2_produtos[n].qtd);
  }

}

void insertion(char vetor[][64], int vetor1[], int n)
{
  int i;
  int j;
  int k1;
  char k[64];
  for (i = 1; i < n; i++)
  {
    strcpy(k, vetor[i]);
    k1 = vetor1[i];
    j = i - 1;
    while ((j >= 0) && (strcmp(k, vetor[j]) < 0))
    {
      strcpy(vetor[j + 1], vetor[j]);
      vetor1[j + 1] = vetor1[j];
      j = j - 1;
    }

    strcpy(vetor[j + 1], k);
    vetor1[j + 1] = k1;
  }

}

