#include "/home/fmarques/sbugs/projects/alunos/lib/stubs.h"
/*File generated by PreProcessor.py*/


#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "equipa.h"
#include "jogo.h"
#include "string_list.h"
#include "strdup.h"


char str[1023];
char e1[1023];
char e2[1023];
int NL = 1;
void comm_A(HT_E Equipas, link *leaderboard)
{
  for (int str_index = 0; str_index < 10; str_index++)
  {
    str[str_index] = new_sym_var(sizeof(char) * 8);
  }

  str[10 - 1] = '\0';
  if (searchEquipa(Equipas, str) != 0)
  {
    printf("%d Equipa existente.\n", NL);
    return;
  }
  else
  {
    
  }

  insertEquipa(Equipas, str);
  insertSorted(leaderboard, str);
}

void comm_P(HT_E Equipas)
{
  Equipa *ptr;
  for (int str_index = 0; str_index < 10; str_index++)
  {
    str[str_index] = new_sym_var(sizeof(char) * 8);
  }

  str[10 - 1] = '\0';
  ptr = searchEquipa(Equipas, str);
  if (ptr == 0)
  {
    printf("%d Equipa inexistente.\n", NL);
    return;
  }
  else
  {
    
  }

  printf("%d %s %d\n", NL, ptr->name, ptr->wins);
}

void comm_a(HT_J Jogos, HT_E Equipas, link *inputJogos)
{
  int s1;
  int s2;
  Equipa *ptr_e1;
  Equipa *ptr_e2;
  Jogo *ptr;
  for (int str_index = 0; str_index < 10; str_index++)
  {
    str[str_index] = new_sym_var(sizeof(char) * 8);
  }

  str[10 - 1] = '\0';
  for (int e1_index = 0; e1_index < 10; e1_index++)
  {
    e1[e1_index] = new_sym_var(sizeof(char) * 8);
  }

  e1[10 - 1] = '\0';
  for (int e2_index = 0; e2_index < 10; e2_index++)
  {
    e2[e2_index] = new_sym_var(sizeof(char) * 8);
  }

  e2[10 - 1] = '\0';
  s1 = new_sym_var(sizeof(int) * 8);
  s2 = new_sym_var(sizeof(int) * 8);
  ptr_e1 = searchEquipa(Equipas, e1);
  ptr_e2 = searchEquipa(Equipas, e2);
  if ((ptr_e1 == 0) || (ptr_e2 == 0))
  {
    printf("%d Equipa inexistente.\n", NL);
    return;
  }
  else
  {
    
  }

  ptr = searchJogo(Jogos, str);
  if (ptr != 0)
  {
    printf("%d Jogo existente.\n", NL);
    return;
  }
  else
  {
    
  }

  insertJogo(Jogos, str, e1, e2, s1, s2);
  append(inputJogos, str);
  if (s1 > s2)
  {
    incWin(Equipas, e1, 1);
  }
  else
  {
    if (s1 < s2)
    {
      incWin(Equipas, e2, 1);
    }
    else
    {
      
    }

  }

}

void comm_p(HT_J Jogos)
{
  Jogo *ptr;
  for (int str_index = 0; str_index < 10; str_index++)
  {
    str[str_index] = new_sym_var(sizeof(char) * 8);
  }

  str[10 - 1] = '\0';
  ptr = searchJogo(Jogos, str);
  if (ptr == 0)
  {
    printf("%d Jogo inexistente.\n", NL);
    return;
  }
  else
  {
    
  }

  printf("%d %s %s %s %d %d\n", NL, ptr->name, ptr->equipa1, ptr->equipa2, ptr->score1, ptr->score2);
}

void comm_l(HT_J Jogos, link *inputJogos)
{
  link x;
  Jogo *ptr;
  for (x = *inputJogos; x != 0; x = x->next)
  {
    ptr = searchJogo(Jogos, x->str);
    printf("%d %s %s %s %d %d\n", NL, ptr->name, ptr->equipa1, ptr->equipa2, ptr->score1, ptr->score2);
  }

}

void comm_r(HT_J Jogos, HT_E Equipas, link *inputJogos)
{
  Jogo *ptr;
  for (int str_index = 0; str_index < 10; str_index++)
  {
    str[str_index] = new_sym_var(sizeof(char) * 8);
  }

  str[10 - 1] = '\0';
  ptr = searchJogo(Jogos, str);
  if (ptr == 0)
  {
    printf("%d Jogo inexistente.\n", NL);
    return;
  }
  else
  {
    
  }

  if (ptr->score1 > ptr->score2)
  {
    incWin(Equipas, ptr->equipa1, 0);
  }
  else
  {
    if (ptr->score1 < ptr->score2)
    {
      incWin(Equipas, ptr->equipa2, 0);
    }
    else
    {
      
    }

  }

  removeJogo(Jogos, str);
  removeStr(inputJogos, str);
}

void comm_s(HT_J Jogos, HT_E Equipas)
{
  int s1;
  int s2;
  Jogo *ptr;
  for (int str_index = 0; str_index < 10; str_index++)
  {
    str[str_index] = new_sym_var(sizeof(char) * 8);
  }

  str[10 - 1] = '\0';
  s1 = new_sym_var(sizeof(int) * 8);
  s2 = new_sym_var(sizeof(int) * 8);
  ptr = searchJogo(Jogos, str);
  if (ptr == 0)
  {
    printf("%d Jogo inexistente.\n", NL);
    return;
  }
  else
  {
    
  }

  if (ptr->score1 > ptr->score2)
  {
    incWin(Equipas, ptr->equipa1, 0);
  }
  else
  {
    if (ptr->score1 < ptr->score2)
    {
      incWin(Equipas, ptr->equipa2, 0);
    }
    else
    {
      
    }

  }

  if (s1 > s2)
  {
    incWin(Equipas, ptr->equipa1, 1);
  }
  else
  {
    if (s1 < s2)
    {
      incWin(Equipas, ptr->equipa2, 1);
    }
    else
    {
      
    }

  }

  ptr->score1 = s1;
  ptr->score2 = s2;
}

void comm_g(HT_E Equipas, link *leaderboard)
{
  int max = 0;
  int i;
  link_e x;
  link y;
  Equipa *ptr;
  for (i = 0; i < Equipas->M; i++)
  {
    for (x = Equipas->L[i]; x != 0; x = x->next)
    {
      if (x->e.wins > max)
      {
        max = x->e.wins;
      }
      else
      {
        
      }

    }

  }

  printf("%d Melhores %d\n", NL, max);
  for (y = *leaderboard; y != 0; y = y->next)
  {
    ptr = searchEquipa(Equipas, y->str);
    if (ptr->wins == max)
    {
      printf("%d * %s\n", NL, ptr->name);
    }
    else
    {
      
    }

  }

}

int main(void)
{
  HT_J Jogos = initJogo(10);
  HT_E Equipas = initEquipa(10);
  link inputJogos = 0;
  link leaderboard = 0;
  char c = getchar();
  while (c != 'x')
  {
    switch (c)
    {
      case 'a':
        comm_a(Jogos, Equipas, &inputJogos);
        NL++;
        break;

      case 'l':
        comm_l(Jogos, &inputJogos);
        NL++;
        break;

      case 'p':
        comm_p(Jogos);
        NL++;
        break;

      case 'r':
        comm_r(Jogos, Equipas, &inputJogos);
        NL++;
        break;

      case 's':
        comm_s(Jogos, Equipas);
        NL++;
        break;

      case 'A':
        comm_A(Equipas, &leaderboard);
        NL++;
        break;

      case 'P':
        comm_P(Equipas);
        NL++;
        break;

      case 'g':
        comm_g(Equipas, &leaderboard);
        NL++;
        break;

    }

    c = getchar();
  }

  return 0;
}

