#include "/home/fmarques/sbugs/projects/alunos/lib/stubs.h"
/*File generated by PreProcessor.py*/


#include <stdlib.h>
#include "games_ht.h"


Game *G_init()
{
  int i;
  Game *games = malloc(48611 * (sizeof(Game)));
  for (i = 0; i < 48611; i++)
    games[i] = 0;

  return games;
}

void G_insert(Game *games, Game g)
{
  int i = hash(g->name, 48611);
  while (games[i])
    i = (i + 1) % 48611;

  games[i] = g;
}

int G_index(Game *games, char *name)
{
  int i = hash(name, 48611);
  while (games[i])
  {
    if (strcmp(games[i]->name, name) == 0)
    {
      return i;
    }
    else
    {
      i = (i + 1) % 48611;
    }

  }

  return -1;
}

Game G_search(Game *games, char *name)
{
  int i = G_index(games, name);
  if (i != (-1))
  {
    return games[i];
  }
  else
  {
    return 0;
  }

}

void G_delete(Game *games, char *name)
{
  Game aux;
  int j;
  int i = G_index(games, name);
  if (i == (-1))
  {
    return;
  }
  else
  {
    
  }

  freeGame(games[i]);
  games[i] = 0;
  for (j = (i + 1) % 48611; games[j]; j = (j + 1) % 48611)
  {
    aux = games[j];
    games[j] = 0;
    G_insert(games, aux);
  }

}

void G_destroy(Game *games)
{
  int i;
  for (i = 0; i < 48611; i++)
    if (games[i])
  {
    freeGame(games[i]);
  }
  else
  {
    
  }


  free(games);
}

