#include "/home/fmarques/sbugs/projects/alunos/lib/stubs.h"
/*File generated by PreProcessor.py*/


#include <stdio.h>
#include <stdlib.h>
#include "defs.h"
#include "cmds.h"


void init(System system)
{
  system->teams = T_init(48611);
  system->games = G_init(48611);
  system->games_dl = mk_list();
}

void destroy(System system)
{
  dll_destroy(system->games_dl);
  G_destroy(system->games);
  T_destroy(system->teams);
  free(system);
}

char rd_ws()
{
  int w = getchar();
  if (((w != ' ') && (w != '\n')) && (w != EOF))
  {
    puts("whitespace expected");
  }
  else
  {
    
  }

  return w;
}

int main()
{
  int cmd;
  long c = 1;
  System system = malloc(sizeof(struct system_struct));
  init(system);
  while ((cmd = getchar()) != 'x')
  {
    switch (cmd)
    {
      case 'a':
        cmd_a(c, system);
        break;

      case 'A':
        cmd_A(c, system);
        break;

      case 'l':
        cmd_l(c, system);
        break;

      case 'p':
        cmd_p(c, system);
        break;

      case 'P':
        cmd_P(c, system);
        break;

      case 'r':
        cmd_r(c, system);
        break;

      case 's':
        cmd_s(c, system);
        break;

      case 'g':
        cmd_g(c, system);
        break;

    }

    c++;
    rd_ws();
  }

  destroy(system);
  return 0;
}

