/*File generated by PreProcessor.py*/


#include <stdio.h>
#include <stdlib.h>
#include <string.h>


int solve(int ave, int rua, int aven, int ruan, int supn, int cidn, int tol, int local[supn][2], int matriz[aven][ruan], int mask[aven][ruan], int localcount)
{
  if (((((((ave < 0) || (ave >= aven)) || (rua < 0)) || (rua >= ruan)) || (cidn == 0)) || (tol < 0)) || (((matriz[ave][rua] == 1) && (ave != local[localcount][0])) && (rua != local[localcount][1])))
  {
    return 0;
  }
  else
  {
    
  }

  if (mask[ave][rua] == 1)
  {
    if ((localcount == (supn - 1)) || ((ave != local[localcount][0]) && (rua != local[localcount][1])))
    {
      return 0;
    }
    else
    {
      
    }

    return solve(local[localcount + 1][0], local[localcount + 1][1], aven, ruan, supn, cidn, tol - 1, local, matriz, mask, localcount + 1);
  }
  else
  {
    
  }

  int max = 0;
  int a;
  mask[ave][rua] = 1;
  if (matriz[ave][rua] == 2)
  {
    if (localcount == (supn - 1))
    {
      mask[ave][rua] = 0;
      return 1;
    }
    else
    {
      
    }

    a = solve(local[localcount + 1][0], local[localcount + 1][1], aven, ruan, supn, cidn - 1, tol, local, matriz, mask, localcount + 1) + 1;
    mask[ave][rua] = 0;
    return a;
  }
  else
  {
    a = solve(ave - 1, rua, aven, ruan, supn, cidn, tol, local, matriz, mask, localcount);
    if (a > max)
    {
      max = a;
    }
    else
    {
      
    }

    if (max != cidn)
    {
      a = solve(ave + 1, rua, aven, ruan, supn, cidn, (tol - max) + 1, local, matriz, mask, localcount);
    }
    else
    {
      
    }

    if (a > max)
    {
      max = a;
    }
    else
    {
      
    }

    if (max != cidn)
    {
      a = solve(ave, rua - 1, aven, ruan, supn, cidn, (tol - max) + 1, local, matriz, mask, localcount);
    }
    else
    {
      
    }

    if (a > max)
    {
      max = a;
    }
    else
    {
      
    }

    if (max != cidn)
    {
      a = solve(ave, rua + 1, aven, ruan, supn, cidn, (tol - max) + 1, local, matriz, mask, localcount);
    }
    else
    {
      
    }

    if (a > max)
    {
      max = a;
    }
    else
    {
      
    }

    if ((((localcount < (supn - 1)) && (ave == local[localcount][0])) && (rua == local[localcount][1])) && (max != cidn))
    {
      mask[ave][rua] = 0;
      a = solve(local[localcount + 1][0], local[localcount + 1][1], aven, ruan, supn, cidn, (tol - max) + 1, local, matriz, mask, localcount + 1);
      if (a > max)
      {
        max = a;
      }
      else
      {
        
      }

    }
    else
    {
      
    }

    mask[ave][rua] = 0;
    return max;
  }

}

int main()
{
  int aven;
  int ruan;
  int supn;
  int cidn;
  int d1;
  int d2;
  int i;
  int j;
  int count;
  aven = new_sym_var(sizeof(int) * 8);
  ruan = new_sym_var(sizeof(int) * 8);
  int matriz[aven][ruan];
  for (i = 0; i < aven; ++i)
  {
    for (j = 0; j < ruan; ++j)
    {
      matriz[i][j] = 0;
    }

  }

  int mask[aven][ruan];
  for (i = 0; i < aven; ++i)
  {
    for (j = 0; j < ruan; ++j)
    {
      mask[i][j] = 0;
    }

  }

  supn = new_sym_var(sizeof(int) * 8);
  cidn = new_sym_var(sizeof(int) * 8);
  if ((supn == 0) || (cidn == 0))
  {
    printf("0\n");
    return 0;
  }
  else
  {
    
  }

  int localtemp[supn][2];
  count = 0;
  for (i = 0; i < supn; ++i)
  {
    d1 = new_sym_var(sizeof(int) * 8);
    d2 = new_sym_var(sizeof(int) * 8);
    if (matriz[d1 - 1][d2 - 1] == 0)
    {
      matriz[d1 - 1][d2 - 1] = 1;
      localtemp[count][0] = d1 - 1;
      localtemp[count][1] = d2 - 1;
      count++;
    }
    else
    {
      
    }

  }

  supn = count;
  int local[supn][2];
  for (i = 0; i < supn; ++i)
  {
    local[i][0] = localtemp[i][0];
    local[i][1] = localtemp[i][1];
  }

  count = 0, j = 0;
  for (i = 0; i < cidn; ++i)
  {
    d1 = new_sym_var(sizeof(int) * 8);
    d2 = new_sym_var(sizeof(int) * 8);
    if (matriz[d1 - 1][d2 - 1] == 1)
    {
      matriz[d1 - 1][d2 - 1] = 3;
      count++;
      mask[d1 - 1][d2 - 1] = 1;
    }
    else
    {
      if (matriz[d1 - 1][d2 - 1] == 0)
      {
        matriz[d1 - 1][d2 - 1] = 2;
        j++;
      }
      else
      {
        
      }

    }

  }

  cidn = j;
  printf("%d\n", count + solve(local[0][0], local[0][1], aven, ruan, supn, cidn, supn, local, matriz, mask, 0));
  return 0;
}

