/*File generated by PreProcessor.py*/


#include "gestao_jogos.h"


void a_adicionaNovoJogo(lista_jogo *lst_jogo, Item **hashtable_jogo, Item **hashtable_equipa, int contador)
{
  char nome[1023];
  char equipa1[1023];
  char equipa2[1023];
  int score1;
  int score2;
  for (int nome_index = 0; nome_index < 10; nome_index++)
  {
    nome[nome_index] = new_sym_var(sizeof(char) * 8);
  }

  nome[10 - 1] = '\0';
  for (int equipa1_index = 0; equipa1_index < 10; equipa1_index++)
  {
    equipa1[equipa1_index] = new_sym_var(sizeof(char) * 8);
  }

  equipa1[10 - 1] = '\0';
  for (int equipa2_index = 0; equipa2_index < 10; equipa2_index++)
  {
    equipa2[equipa2_index] = new_sym_var(sizeof(char) * 8);
  }

  equipa2[10 - 1] = '\0';
  score1 = new_sym_var(sizeof(int) * 8);
  score2 = new_sym_var(sizeof(int) * 8);
  if (procura_item(nome, hashtable_jogo))
  {
    printf("%d Jogo existente.\n", contador);
  }
  else
  {
    if ((!procura_item(equipa1, hashtable_equipa)) || (!procura_item(equipa2, hashtable_equipa)))
    {
      printf("%d Equipa inexistente.\n", contador);
    }
    else
    {
      Item *novo_jogo = cria_jogo(nome, equipa1, equipa2, score1, score2);
      insere_hashtable(novo_jogo, hashtable_jogo);
      adiciona_vitoria(hashtable_equipa, novo_jogo);
      if (lst_jogo->last)
      {
        novo_jogo->prev = lst_jogo->last;
        lst_jogo->last->next = novo_jogo;
      }
      else
      {
        
      }

      lst_jogo->last = novo_jogo;
      if (!lst_jogo->head)
      {
        lst_jogo->head = novo_jogo;
      }
      else
      {
        
      }

    }

  }

}

Item *A_adicionaNovaEquipa(Item *head_equipa, Item **hashtable, int contador)
{
  char nome[1023];
  for (int nome_index = 0; nome_index < 10; nome_index++)
  {
    nome[nome_index] = new_sym_var(sizeof(char) * 8);
  }

  nome[10 - 1] = '\0';
  if (procura_item(nome, hashtable))
  {
    printf("%d Equipa existente.\n", contador);
    return head_equipa;
  }
  else
  {
    Item *nova_equipa = cria_equipa(nome);
    insere_hashtable(nova_equipa, hashtable);
    if (!head_equipa)
    {
      return nova_equipa;
    }
    else
    {
      if (strcmp(nova_equipa->nome, head_equipa->nome) < 0)
      {
        nova_equipa->next = head_equipa;
        return nova_equipa;
      }
      else
      {
        Item *anterior = head_equipa;
        Item *head = head_equipa;
        head_equipa = head_equipa->next;
        while (head_equipa && (strcmp(nova_equipa->nome, head_equipa->nome) > 0))
        {
          anterior = head_equipa;
          head_equipa = head_equipa->next;
        }

        nova_equipa->next = head_equipa;
        anterior->next = nova_equipa;
        return head;
      }

    }

  }

}

void l_listaTodosJogosPorOrdem(lista_jogo *lst_jogo, int contador)
{
  Item *j = lst_jogo->head;
  while (j)
  {
    printf("%d %s %s %s %d %d\n", contador, j->nome, j->equipa1, j->equipa2, j->score1, j->score2);
    j = j->next;
  }

}

void p_procuraJogo(Item **hashtable, int contador)
{
  Item *jogo;
  char nome[1023];
  for (int nome_index = 0; nome_index < 10; nome_index++)
  {
    nome[nome_index] = new_sym_var(sizeof(char) * 8);
  }

  nome[10 - 1] = '\0';
  jogo = procura_item(nome, hashtable);
  if (jogo)
  {
    printf("%d %s %s %s %d %d\n", contador, jogo->nome, jogo->equipa1, jogo->equipa2, jogo->score1, jogo->score2);
  }
  else
  {
    printf("%d Jogo inexistente.\n", contador);
  }

}

void P_procuraEquipa(Item **hashtable, int contador)
{
  char nome[1023];
  Item *equipa;
  for (int nome_index = 0; nome_index < 10; nome_index++)
  {
    nome[nome_index] = new_sym_var(sizeof(char) * 8);
  }

  nome[10 - 1] = '\0';
  equipa = procura_item(nome, hashtable);
  if (equipa)
  {
    printf("%d %s %d\n", contador, nome, equipa->vitorias);
  }
  else
  {
    printf("%d Equipa inexistente.\n", contador);
  }

}

void r_apagaJogo(lista_jogo *lst_jogo, Item **hashtable_jogo, Item **hashtable_equipa, int contador)
{
  char nome[1023];
  for (int nome_index = 0; nome_index < 10; nome_index++)
  {
    nome[nome_index] = new_sym_var(sizeof(char) * 8);
  }

  nome[10 - 1] = '\0';
  if (!apaga_jogo(nome, hashtable_jogo, hashtable_equipa, lst_jogo))
  {
    printf("%d Jogo inexistente.\n", contador);
  }
  else
  {
    
  }

}

void s_alteraPontuacao(Item **hashtable_jogo, Item **hashtable_equipa, int contador)
{
  Item *jogo;
  int score1;
  int score2;
  char nome[1023];
  for (int nome_index = 0; nome_index < 10; nome_index++)
  {
    nome[nome_index] = new_sym_var(sizeof(char) * 8);
  }

  nome[10 - 1] = '\0';
  score1 = new_sym_var(sizeof(int) * 8);
  score2 = new_sym_var(sizeof(int) * 8);
  if (!(jogo = procura_item(nome, hashtable_jogo)))
  {
    printf("%d Jogo inexistente.\n", contador);
  }
  else
  {
    retira_vitoria(hashtable_equipa, jogo);
    jogo->score1 = score1;
    jogo->score2 = score2;
    adiciona_vitoria(hashtable_equipa, jogo);
  }

}

void g_encontraEquipasMaisVitorias(Item *head_equipa, int contador)
{
  Item *equipa = head_equipa;
  int maior_vitoria = 0;
  while (equipa)
  {
    if (equipa->vitorias > maior_vitoria)
    {
      maior_vitoria = equipa->vitorias;
    }
    else
    {
      
    }

    equipa = equipa->next;
  }

  if (head_equipa)
  {
    printf("%d Melhores %d\n", contador, maior_vitoria);
  }
  else
  {
    
  }

  while (head_equipa)
  {
    if (head_equipa->vitorias == maior_vitoria)
    {
      printf("%d * %s\n", contador, head_equipa->nome);
    }
    else
    {
      
    }

    head_equipa = head_equipa->next;
  }

}

