/*File generated by PreProcessor.py*/


#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "listajogos.h"


lista cria_lista_jogos()
{
  lista ls = malloc(sizeof(struct listajogos));
  ls->head = (ls->last = 0);
  return ls;
}

linkjg add_lista(lista l, jogo *novo_jogo)
{
  linkjg new = malloc(sizeof(struct nodejg));
  new->next = 0;
  new->jogo = novo_jogo;
  if (l->head == 0)
  {
    {
      l->head = (l->last = new);
      new->prev = 0;
    }
  }
  else
  {
    {
      l->last->next = new;
      new->prev = l->last;
      l->last = new;
    }
  }

  return new;
}

void remove_lista(linkjg no, lista l)
{
  if (no == l->head)
  {
    {
      l->head = l->head->next;
    }
  }
  else
  {
    if (no == l->last)
    {
      {
        l->last = l->last->prev;
        l->last->next = 0;
      }
    }
    else
    {
      {
        no->prev->next = no->next;
        no->next->prev = no->prev;
      }
    }

  }

  free(no->jogo->nome);
  free(no->jogo->equipa1);
  free(no->jogo->equipa2);
  free(no->jogo);
  free(no);
}

