#include "/home/fmarques/sbugs/projects/alunos/lib/stubs.h"
/*File generated by PreProcessor.py*/


#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <string.h>
#include "jogos.h"


jogo *procuraJogo(hashJ *s, char *nome)
{
  int chave;
  jogo *auxx;
  jogo *auxy;
  chave = hash(nome);
  auxx = s->entradas[chave];
  while (auxx != 0)
  {
    if (strcmp(auxx->nome, nome) == 0)
    {
      return auxx;
    }
    else
    {
      
    }

    auxy = auxx;
    auxx = auxy->next;
  }

  return 0;
}

int adicionaJogo(hashJ *tabelaJogos, hashE *tabelaEquipas, char *nome, char *nomeequipa1, char *nomeequipa2, int resultado1, int resultado2)
{
  equipa *equipa1;
  equipa *equipa2;
  jogo *jogo1;
  jogo *quilho;
  int chave;
  jogo1 = procuraJogo(tabelaJogos, nome);
  if (jogo1 != 0)
  {
    return 1;
  }
  else
  {
    
  }

  equipa1 = procuraEquipa(tabelaEquipas, nomeequipa1);
  equipa2 = procuraEquipa(tabelaEquipas, nomeequipa2);
  if ((equipa1 == 0) || (equipa2 == 0))
  {
    return 2;
  }
  else
  {
    
  }

  chave = hash(nome);
  jogo1 = tabelaJogos->entradas[chave];
  if (jogo1 == 0)
  {
    jogo1 = malloc(sizeof(jogo));
    jogo1->nome = malloc(strlen(nome) + 1);
    strcpy(jogo1->nome, nome);
    jogo1->equipa1 = malloc(strlen(nomeequipa1) + 1);
    strcpy(jogo1->equipa1, nomeequipa1);
    jogo1->equipa2 = malloc(strlen(nomeequipa2) + 1);
    strcpy(jogo1->equipa2, nomeequipa2);
    if (resultado1 > resultado2)
    {
      adicionaVitoria(tabelaEquipas, nomeequipa1);
    }
    else
    {
      
    }

    if (resultado1 < resultado2)
    {
      adicionaVitoria(tabelaEquipas, nomeequipa2);
    }
    else
    {
      
    }

    jogo1->pontos1 = resultado1;
    jogo1->pontos2 = resultado2;
    tamanhoLista++;
    listaL = realloc(listaL, (sizeof(jogo)) * tamanhoLista);
    listaL[tamanhoLista - 1] = *jogo1;
    tabelaJogos->entradas[chave] = jogo1;
    return 0;
  }
  else
  {
    
  }

  while (jogo1 != 0)
  {
    quilho = jogo1;
    jogo1 = quilho->next;
  }

  jogo1 = malloc(sizeof(jogo));
  jogo1->nome = malloc(strlen(nome) + 1);
  strcpy(jogo1->nome, nome);
  jogo1->equipa1 = malloc(strlen(nomeequipa1) + 1);
  strcpy(jogo1->equipa1, nomeequipa1);
  jogo1->equipa2 = malloc(strlen(nomeequipa2) + 1);
  strcpy(jogo1->equipa2, nomeequipa2);
  if (resultado1 > resultado2)
  {
    adicionaVitoria(tabelaEquipas, nomeequipa1);
  }
  else
  {
    
  }

  if (resultado1 < resultado2)
  {
    adicionaVitoria(tabelaEquipas, nomeequipa2);
  }
  else
  {
    
  }

  jogo1->pontos1 = resultado1;
  jogo1->pontos2 = resultado2;
  tamanhoLista++;
  listaL = realloc(listaL, (sizeof(jogo)) * tamanhoLista);
  listaL[tamanhoLista - 1] = *jogo1;
  return 0;
}

hashJ *criaHash()
{
  int i;
  hashJ *anexo = malloc(sizeof(hashJ));
  anexo->entradas = malloc((sizeof(jogo *)) * 1000);
  for (i = 0; i < 1000; i++)
  {
    anexo->entradas[i] = 0;
  }

  return anexo;
}

void imprimeLista(int nl)
{
  int i;
  for (i = 0; i < tamanhoLista; i++)
  {
    printf("%d %s %s %s %d %d\n", nl, listaL[i].nome, listaL[i].equipa1, listaL[i].equipa2, listaL[i].pontos1, listaL[i].pontos2);
  }

}

void removeLista(char *nome)
{
  int i;
  int t;
  for (i = 0; i < tamanhoLista; i++)
  {
    if (strcmp(listaL[i].nome, nome) == 0)
    {
      t = i;
      break;
    }
    else
    {
      
    }

  }

  for (i = t; i < (tamanhoLista - 1); i++)
  {
    listaL[i] = listaL[i + 1];
  }

  tamanhoLista--;
  listaL = realloc(listaL, (sizeof(jogo)) * tamanhoLista);
}

void removeJogo(hashJ *lolada, hashE *e, char *nome, int nl)
{
  int chave;
  jogo *jogoz;
  jogo *outro;
  chave = hash(nome);
  jogoz = lolada->entradas[chave];
  if (!jogoz)
  {
    printf("%d Jogo inexistente.\n", nl);
    return;
  }
  else
  {
    
  }

  if (strcmp(lolada->entradas[chave]->nome, nome) == 0)
  {
    if (lolada->entradas[chave]->pontos1 > lolada->entradas[chave]->pontos2)
    {
      retiraVitoria(e, lolada->entradas[chave]->equipa1);
    }
    else
    {
      
    }

    if (lolada->entradas[chave]->pontos1 < lolada->entradas[chave]->pontos2)
    {
      retiraVitoria(e, lolada->entradas[chave]->equipa2);
    }
    else
    {
      
    }

    lolada->entradas[chave] = lolada->entradas[chave]->next;
    removeLista(nome);
    free(jogoz->nome);
    free(jogoz);
    return;
  }
  else
  {
    
  }

  outro = jogoz;
  jogoz = outro->next;
  while (jogoz != 0)
  {
    if (strcmp(outro->next->nome, nome) == 0)
    {
      outro->next = jogoz->next;
      if (outro->pontos1 > outro->pontos2)
      {
        retiraVitoria(e, outro->equipa1);
      }
      else
      {
        
      }

      if (outro->pontos1 < outro->pontos2)
      {
        retiraVitoria(e, outro->equipa2);
      }
      else
      {
        
      }

      removeLista(nome);
      free(jogoz->nome);
      free(jogoz);
      return;
    }
    else
    {
      
    }

  }

}

void alterapontos(hashJ *omega, hashE *e, char *nome, int pontos1, int pontos2, int nl)
{
  jogo *tau;
  tau = procuraJogo(omega, nome);
  if (!tau)
  {
    printf("%d Jogo inexistente.\n", nl);
    return;
  }
  else
  {
    
  }

  if ((tau->pontos1 > tau->pontos2) && (pontos1 < pontos2))
  {
    retiraVitoria(e, tau->equipa1);
    adicionaVitoria(e, tau->equipa2);
  }
  else
  {
    if ((tau->pontos1 > tau->pontos2) && (pontos1 == pontos2))
    {
      retiraVitoria(e, tau->equipa1);
    }
    else
    {
      if ((tau->pontos1 == tau->pontos2) && (pontos1 > pontos2))
      {
        adicionaVitoria(e, tau->equipa1);
      }
      else
      {
        if ((tau->pontos1 == tau->pontos2) && (pontos1 < pontos2))
        {
          adicionaVitoria(e, tau->equipa2);
        }
        else
        {
          if ((tau->pontos1 < tau->pontos2) && (pontos1 > pontos2))
          {
            adicionaVitoria(e, tau->equipa1);
            retiraVitoria(e, tau->equipa2);
          }
          else
          {
            if ((tau->pontos1 < tau->pontos2) && (pontos1 == pontos2))
            {
              retiraVitoria(e, tau->equipa2);
            }
            else
            {
              
            }

          }

        }

      }

    }

  }

  tau->pontos1 = pontos1;
  tau->pontos2 = pontos2;
}

