#include "/home/fmarques/sbugs/projects/alunos/lib/stubs.h"
/*File generated by PreProcessor.py*/


#include <stdio.h>
#include <string.h>


typedef struct produto
{
  int iden;
  char desc[63];
  int preco;
  int peso;
  int quanti;
} produto;
typedef struct encomenda
{
  produto v_encomendas[200];
  int ide;
  int peso_enc;
} encomenda;
produto armazem[10000];
encomenda encomendas[500];
char vazia[63] = "\0";
void distingue_encomendas(encomenda encomendas[])
{
  int i;
  for (i = 0; i < 500; i++)
  {
    encomendas[i].ide = -1;
  }

}

void distingue_produtos_armazem(produto armazem[])
{
  int i;
  for (i = 0; i < 10000; i++)
  {
    armazem[i].iden = -2;
  }

}

void copia_produtos(produto destino[], produto fonte[])
{
  int i;
  for (i = 0; i < 200; i++)
  {
    destino[i].iden = fonte[i].iden;
    destino[i].peso = fonte[i].peso;
    destino[i].preco = fonte[i].preco;
    destino[i].quanti = fonte[i].quanti;
    strcpy(destino[i].desc, fonte[i].desc);
  }

}

void copia_produto_1(produto destino[], produto fonte[], int l)
{
  destino[l].iden = fonte[l].iden;
  destino[l].peso = fonte[l].peso;
  destino[l].preco = fonte[l].preco;
  destino[l].quanti = fonte[l].quanti;
  strcpy(destino[l].desc, fonte[l].desc);
}

void copia_produto_2(produto destino[], produto fonte[], int j)
{
  destino[0].iden = fonte[j].iden;
  destino[0].peso = fonte[j].peso;
  destino[0].preco = fonte[j].preco;
  destino[0].quanti = fonte[j].quanti;
  strcpy(destino[0].desc, fonte[j].desc);
}

void copia_produto_3(produto destino[], produto fonte[], int j)
{
  destino[j].iden = fonte[j + 1].iden;
  destino[j].peso = fonte[j + 1].peso;
  destino[j].preco = fonte[j + 1].preco;
  destino[j].quanti = fonte[j + 1].quanti;
  strcpy(destino[j].desc, fonte[j + 1].desc);
}

void copia_produto_4(produto destino[], produto fonte[], int j)
{
  destino[j + 1].iden = fonte[0].iden;
  destino[j + 1].peso = fonte[0].peso;
  destino[j + 1].preco = fonte[0].preco;
  destino[j + 1].quanti = fonte[0].quanti;
  strcpy(destino[j + 1].desc, fonte[0].desc);
}

void copia_produtos_5(produto destino[], produto fonte[], int i)
{
  destino[i - 1].iden = fonte[i - 1].iden;
  destino[i - 1].peso = fonte[i - 1].peso;
  destino[i - 1].preco = fonte[i - 1].preco;
  destino[i - 1].quanti = fonte[i - 1].quanti;
  strcpy(destino[i - 1].desc, fonte[i - 1].desc);
}

void copia_produtos_6(produto destino[], produto fonte[], int k, int j)
{
  destino[k].iden = fonte[j].iden;
  destino[k].peso = fonte[j].peso;
  destino[k].preco = fonte[j].preco;
  destino[k].quanti = fonte[j].quanti;
  strcpy(destino[k].desc, fonte[j].desc);
  j--;
}

void copia_produtos_7(produto destino[], produto fonte[], int k, int i)
{
  destino[k].iden = fonte[i].iden;
  destino[k].peso = fonte[i].peso;
  destino[k].preco = fonte[i].preco;
  destino[k].quanti = fonte[i].quanti;
  strcpy(destino[k].desc, fonte[i].desc);
  i++;
}

void copia_produtos_8(produto destino[], produto fonte[], int r, int m, int j)
{
  destino[(r + m) - j].iden = fonte[j + 1].iden;
  destino[(r + m) - j].peso = fonte[j + 1].peso;
  destino[(r + m) - j].preco = fonte[j + 1].preco;
  destino[(r + m) - j].quanti = fonte[j + 1].quanti;
  strcpy(destino[(r + m) - j].desc, fonte[j + 1].desc);
}

int descobre_tamanho(produto armazem[])
{
  int contador = 0;
  int i;
  for (i = 0; i < 10000; i++)
  {
    if (armazem[i].iden != (-2))
    {
      contador++;
    }
    else
    {
      
    }

  }

  return contador;
}

void merge(produto lista[], int l, int m, int r)
{
  int i;
  int j;
  int k;
  produto lista_aux[200];
  for (i = m + 1; i > l; i--)
  {
    copia_produtos_5(lista_aux, lista, i);
  }

  for (j = m; j < r; j++)
  {
    copia_produtos_8(lista_aux, lista, r, m, j);
  }

  for (k = l; k <= r; k++)
  {
    if ((lista_aux[j].quanti > lista_aux[i].quanti) || (i > m))
    {
      copia_produtos_6(lista, lista_aux, k, j);
    }
    else
    {
      copia_produtos_7(lista, lista_aux, k, i);
    }

  }

}

void merge_sort(produto lista[], int l, int r)
{
  if (l < r)
  {
    int meio = ((int) (r + l)) / 2;
    merge_sort(lista, l, meio);
    merge_sort(lista, meio + 1, r);
    merge(lista, l, meio, r);
  }
  else
  {
    
  }

}

void funcao_a(produto armazem[], char descricao[], int preco, int peso, int quantidade)
{
  static int gere_produto;
  strcpy(armazem[gere_produto].desc, descricao);
  armazem[gere_produto].preco = preco;
  armazem[gere_produto].peso = peso;
  armazem[gere_produto].quanti = quantidade;
  armazem[gere_produto].iden = gere_produto;
  printf("Novo produto %d.\n", gere_produto);
  gere_produto++;
}

produto funcao_q(produto armazem[], int idp, int quantidade)
{
  if (armazem[idp].iden == (-2))
  {
    printf("Impossivel adicionar produto %d ao stock. Produto inexistente.\n", idp);
  }
  else
  {
    armazem[idp].quanti += quantidade;
  }

  return armazem[idp];
}

encomenda funcao_N()
{
  static int gere_enc;
  int l;
  int aux;
  for (l = 0; l < 200; l++)
  {
    encomendas[gere_enc].v_encomendas[l].iden = 250;
    strcpy(encomendas[gere_enc].v_encomendas[l].desc, vazia);
    encomendas[gere_enc].v_encomendas[l].preco = 0;
    encomendas[gere_enc].v_encomendas[l].peso = 0;
    encomendas[gere_enc].v_encomendas[l].quanti = 0;
  }

  encomendas[gere_enc].ide = gere_enc;
  encomendas[gere_enc].peso_enc = 0;
  printf("Nova encomenda %d.\n", gere_enc);
  aux = gere_enc;
  gere_enc++;
  return encomendas[aux];
}

encomenda funcao_A(encomenda encomendas[], int ide, int idp, int quantidade)
{
  static int i;
  if (encomendas[ide].ide == (-1))
  {
    printf("Impossivel adicionar produto %d a encomenda %d. Encomenda inexistente.\n", idp, ide);
  }
  else
  {
    if (armazem[idp].iden == (-2))
    {
      printf("Impossivel adicionar produto %d a encomenda %d. Produto inexistente.\n", idp, ide);
    }
    else
    {
      if (quantidade > armazem[idp].quanti)
      {
        printf("Impossivel adicionar produto %d a encomenda %d. Quantidade em stock insuficiente.\n", idp, ide);
      }
      else
      {
        if ((encomendas[ide].peso_enc + armazem[idp].peso) > 200)
        {
          printf("Impossivel adicionar produto %d a encomenda %d. Peso da encomenda excede o maximo de 200.\n", idp, ide);
        }
        else
        {
          encomendas[ide].v_encomendas[i].preco = armazem[idp].preco;
          encomendas[ide].v_encomendas[i].quanti = armazem[idp].quanti;
          encomendas[ide].v_encomendas[i].peso = armazem[idp].peso;
          encomendas[ide].v_encomendas[i].iden = armazem[idp].iden;
          strcpy(encomendas[ide].v_encomendas[i].desc, armazem[idp].desc);
          encomendas[ide].peso_enc += armazem[idp].peso;
          armazem[idp].quanti -= quantidade;
          i++;
        }

      }

    }

  }

  return encomendas[ide];
}

produto funcao_r(produto armazem[], int idp, int quantidade)
{
  if (armazem[idp].iden == (-2))
  {
    printf("Impossivel adicionar produto %d ao stock. Produto inexistente.\n", idp);
  }
  else
  {
    if ((armazem[idp].quanti - quantidade) < 0)
    {
      printf("Impossivel remover %d unidades do produto %d do stock. Quantidade insuficiente.\n", quantidade, idp);
    }
    else
    {
      armazem[idp].quanti -= quantidade;
    }

  }

  return armazem[idp];
}

encomenda funcao_R(encomenda encomendas[], int ide, int idp)
{
  int i;
  if (encomendas[ide].ide == (-1))
  {
    printf("Impossivel remover produto %d a encomenda %d. Encomenda inexistente.\n", idp, ide);
  }
  else
  {
    if (encomendas[ide].v_encomendas[idp].iden == 250)
    {
      printf("Impossivel remover produto %d a encomenda %d. Produto inexistente.\n", idp, ide);
    }
    else
    {
      for (i = 0; i < 10000; i++)
      {
        if (encomendas[ide].v_encomendas[i].iden == idp)
        {
          armazem[idp].quanti += encomendas[ide].v_encomendas[i].quanti;
          encomendas[ide].v_encomendas[i].iden = 250;
          encomendas[ide].v_encomendas[i].preco = 0;
          encomendas[ide].v_encomendas[i].peso = 0;
          encomendas[ide].v_encomendas[i].quanti = 0;
          strcpy(encomendas[ide].v_encomendas[i].desc, vazia);
        }
        else
        {
          
        }

      }

    }

  }

  return encomendas[ide];
}

void funcao_C(encomenda encomendas[], int ide)
{
  int total = 0;
  int m;
  if (encomendas[ide].ide == (-1))
  {
    printf("Impossivel calcular custo da encomenda %d. Encomenda inexistente.\n", ide);
  }
  else
  {
    for (m = 0; m < 500; m++)
    {
      total += encomendas[ide].v_encomendas[m].preco;
    }

  }

  printf("Custo da encomenda %d %d.\n", ide, total);
}

void funcao_p(produto armazem[], int idp, int valor_numerico)
{
  int i;
  int j;
  int k;
  if (armazem[idp].iden == (-2))
  {
    printf("Impossivel alterar preco do produto %d. Produto inexistente.\n", idp);
  }
  else
  {
    for (k = 0; k < 10000; k++)
    {
      if (armazem[k].iden == idp)
      {
        armazem[k].preco = valor_numerico;
      }
      else
      {
        
      }

    }

    for (i = 0; i < 500; i++)
    {
      for (j = 0; j < 200; j++)
      {
        if (encomendas[i].v_encomendas[j].iden == idp)
        {
          encomendas[i].v_encomendas[j].preco = valor_numerico;
        }
        else
        {
          
        }

      }

    }

  }

}

void funcao_E(encomenda encomendas[], int ide, int idp)
{
  int i;
  if (encomendas[ide].ide == (-1))
  {
    printf("Impossivel listar encomenda %d. Encomenda inexistente.\n", ide);
  }
  else
  {
    if (encomendas[ide].v_encomendas[idp].iden == 250)
    {
      printf("Impossivel listar produto %d. Produto inexistente.\n", idp);
    }
    else
    {
      for (i = 0; i < 200; i++)
      {
        if (encomendas[ide].v_encomendas[i].iden == idp)
        {
          printf("%s %d\n", encomendas[ide].v_encomendas[i].desc, encomendas[ide].v_encomendas[i].quanti);
        }
        else
        {
          
        }

      }

    }

  }

}

void funcao_m(encomenda encomendas[], produto armazem[], int idp)
{
  int i;
  int j;
  int m;
  int k;
  int contador[500];
  int maior = 0;
  int ide_pretendido;
  int quantidade_do_idp = 0;
  int encomendas_nao_iniciadas = 0;
  int contador_idp_inexistente = 0;
  int contador_aux = 0;
  for (m = 0; m < 500; m++)
  {
    contador[m] = 0;
  }

  for (k = 0; k < 10000; k++)
  {
    if (armazem[k].iden != idp)
    {
      contador_aux++;
    }
    else
    {
      
    }

  }

  if (contador_aux == 10000)
  {
    printf("Impossivel listar maximo do produto %d. Produto inexistente.", idp);
  }
  else
  {
    
  }

  for (i = 0; i < 500; i++)
  {
    if (encomendas[i].ide == (-1))
    {
      encomendas_nao_iniciadas++;
    }
    else
    {
      
    }

    for (j = 0; j < 200; j++)
    {
      if (encomendas[i].v_encomendas[j].iden == idp)
      {
        contador[i]++;
        if (contador[i] > maior)
        {
          maior = contador[i];
        }
        else
        {
          
        }

      }
      else
      {
        if (encomendas[i].v_encomendas[j].iden != idp)
        {
          contador_idp_inexistente++;
          if (contador_idp_inexistente == 10000)
          {
            break;
          }
          else
          {
            
          }

        }
        else
        {
          
        }

      }

    }

    if (contador[i] == maior)
    {
      ide_pretendido = i;
    }
    else
    {
      
    }

  }

  if (encomendas_nao_iniciadas == 200)
  {
    return;
  }
  else
  {
    
  }

  for (i = 0; i < 200; i++)
  {
    if (encomendas[ide_pretendido].v_encomendas[i].iden == idp)
    {
      quantidade_do_idp += encomendas[ide_pretendido].v_encomendas[i].quanti;
    }
    else
    {
      
    }

  }

  printf("Maximo produto %d %d %d.\n", idp, ide_pretendido, quantidade_do_idp);
}

void funcao_l(produto armazem[])
{
  int i;
  int j;
  int l;
  int k;
  produto novo_armazem[10000];
  produto auxiliar[1];
  int barreira = descobre_tamanho(armazem);
  for (l = 0; l < barreira; l++)
  {
    copia_produto_1(novo_armazem, armazem, l);
  }

  for (i = 0; i < barreira; i++)
  {
    for (j = 0; j < (barreira - 1); j++)
    {
      if (novo_armazem[j].preco > novo_armazem[j + 1].preco)
      {
        copia_produto_2(auxiliar, novo_armazem, j);
        copia_produto_3(novo_armazem, novo_armazem, j);
        copia_produto_4(novo_armazem, auxiliar, j);
      }
      else
      {
        
      }

    }

  }

  printf("Produtos\n");
  for (k = 0; k < barreira; k++)
  {
    printf("*%s %d %d\n", novo_armazem[k].desc, novo_armazem[k].preco, novo_armazem[k].quanti);
  }

}

void funcao_L(encomenda encomendas[], int ide)
{
  if (encomendas[ide].ide == (-1))
  {
    printf("Impossivel listar encomenda %d. Encomenda inexistente.\n", ide);
  }
  else
  {
    int i;
    int r;
    produto lista_de_prod_da_enc[200];
    copia_produtos(lista_de_prod_da_enc, encomendas[ide].v_encomendas);
    r = descobre_tamanho(lista_de_prod_da_enc);
    merge_sort(lista_de_prod_da_enc, 0, r);
    printf("Encomenda %d\n", ide);
    for (i = 0; i < r; i++)
    {
      printf("%s %d %d\n", lista_de_prod_da_enc[i].desc, lista_de_prod_da_enc[i].preco, lista_de_prod_da_enc[i].quanti);
    }

  }

}

int main()
{
  int c;
  int ide;
  int idp;
  int preco_aux;
  int peso_aux;
  int quanti_aux;
  char cadeia_auxiliar[63];
  distingue_produtos_armazem(armazem);
  distingue_encomendas(encomendas);
  while ((c = getchar()) != EOF)
  {
    switch (c)
    {
      case 'a':
        for (int cadeia_auxiliar_index = 0; cadeia_auxiliar_index < 10; cadeia_auxiliar_index++)
      {
        cadeia_auxiliar[cadeia_auxiliar_index] = new_sym_var(sizeof(char) * 8);
      }

        cadeia_auxiliar[10 - 1] = '\0';
        preco_aux = new_sym_var(sizeof(int) * 8);
        peso_aux = new_sym_var(sizeof(int) * 8);
        quanti_aux = new_sym_var(sizeof(int) * 8);
        funcao_a(armazem, cadeia_auxiliar, preco_aux, peso_aux, quanti_aux);
        continue;

      case 'q':
        idp = new_sym_var(sizeof(int) * 8);
        quanti_aux = new_sym_var(sizeof(int) * 8);
        funcao_q(armazem, idp, quanti_aux);
        break;

      case 'N':
        funcao_N();
        break;

      case 'A':
        ide = new_sym_var(sizeof(int) * 8);
        idp = new_sym_var(sizeof(int) * 8);
        quanti_aux = new_sym_var(sizeof(int) * 8);
        funcao_A(encomendas, ide, idp, quanti_aux);
        break;

      case 'r':
        idp = new_sym_var(sizeof(int) * 8);
        quanti_aux = new_sym_var(sizeof(int) * 8);
        funcao_r(armazem, idp, quanti_aux);
        break;

      case 'R':
        ide = new_sym_var(sizeof(int) * 8);
        idp = new_sym_var(sizeof(int) * 8);
        funcao_R(encomendas, ide, idp);
        break;

      case 'C':
        ide = new_sym_var(sizeof(int) * 8);
        funcao_C(encomendas, ide);
        break;

      case 'p':
        idp = new_sym_var(sizeof(int) * 8);
        preco_aux = new_sym_var(sizeof(int) * 8);
        funcao_p(armazem, idp, preco_aux);
        break;

      case 'E':
        ide = new_sym_var(sizeof(int) * 8);
        idp = new_sym_var(sizeof(int) * 8);
        funcao_R(encomendas, ide, idp);
        break;

      case 'm':
        idp = new_sym_var(sizeof(int) * 8);
        funcao_m(encomendas, armazem, idp);
        break;

      case 'l':
        funcao_l(armazem);
        continue;

      case 'L':
        ide = new_sym_var(sizeof(int) * 8);
        funcao_L(encomendas, ide);
        break;

      case 'x':
        return 0;

    }

  }

  return -1;
}

