/*File generated by PreProcessor.py*/


#include "game_struct.h"


void init_hashtbl(game_item *ht_ptr)
{
  int i;
  for (i = 0; i < 1009; i++)
  {
    ht_ptr[i] = (game_item) malloc(sizeof(struct g_item));
    ht_ptr[i]->head = 0;
  }

}

void init_games(game_item **hash_ptr)
{
  *hash_ptr = (game_item *) malloc(1009 * (sizeof(game_item)));
  init_hashtbl(*hash_ptr);
}

void free_node(game_node node)
{
  free_game(node->game);
  free(node);
}

void free_games(game_item *ht_ptr)
{
  int i;
  game_node auxiliar_node;
  for (i = 0; i < 1009; i++)
  {
    while (ht_ptr[i]->head != 0)
    {
      auxiliar_node = ht_ptr[i]->head;
      ht_ptr[i]->head = ht_ptr[i]->head->next;
      free_node(auxiliar_node);
    }

    free(ht_ptr[i]);
  }

  free(ht_ptr);
}

void node_push(game_node *head, game game, game_node *first, game_node *current)
{
  game_node new_node;
  new_node = (game_node) malloc(sizeof(struct g_node));
  new_node->game = game;
  new_node->next = *head;
  new_node->previous = 0;
  if ((*head) != 0)
  {
    (*head)->previous = new_node;
  }
  else
  {
    
  }

  *head = new_node;
  new_node->in_next = 0;
  new_node->in_previous = 0;
  if ((*first) == 0)
  {
    {
      *first = new_node;
      *current = new_node;
    }
  }
  else
  {
    
  }

  *current = new_node;
}

void insert_game(game_item *ht_ptr, game game, game_node *first, game_node *current)
{
  int index = hash_function(game->name);
  node_push(&ht_ptr[index]->head, game, first, current);
}

void print_game(game_node node, int NL)
{
  printf("%d %s %s %s %d %d\n", NL, node->game->name, node->game->team_1->name, node->game->team_2->name, node->game->score_1, node->game->score_2);
}

game_node search_game(game_item *ht_ptr, char *name)
{
  int i;
  game_node node;
  i = hash_function(name);
  node = ht_ptr[i]->head;
  while (node != 0)
  {
    if (strcmp(node->game->name, name) == 0)
    {
      return node;
    }
    else
    {
      
    }

    node = node->next;
  }

  return 0;
}

void delete_ordered(game_node *head, game_node node)
{
  if ((head == 0) || (node == 0))
  {
    return;
  }
  else
  {
    
  }

  if ((*head) == node)
  {
    *head = node->in_next;
  }
  else
  {
    
  }

  if (node->in_next != 0)
  {
    node->in_next->in_previous = node->in_previous;
  }
  else
  {
    
  }

  if (node->in_previous != 0)
  {
    node->in_previous->in_next = node->in_next;
  }
  else
  {
    
  }

}

void delete_game(game_item hashtbl, game_node node)
{
  if ((node->previous == 0) && (node->next == 0))
  {
    {
      hashtbl->head = 0;
      free_node(node);
    }
  }
  else
  {
    if ((node->previous == 0) && (node->next != 0))
    {
      {
        node->next->previous = 0;
        hashtbl->head = node->next;
        free_node(node);
      }
    }
    else
    {
      if ((node->previous != 0) && (node->next != 0))
      {
        {
          node->previous->next = node->next;
          node->next->previous = node->previous;
          free_node(node);
        }
      }
      else
      {
        if ((node->previous != 0) && (node->next == 0))
        {
          {
            node->previous->next = 0;
            free_node(node);
          }
        }
        else
        {
          
        }

      }

    }

  }

}

void update_score(game_node node, int s1, int s2)
{
  int p_s1;
  int p_s2;
  team t1;
  team t2;
  p_s1 = (int) node->game->score_1;
  p_s2 = (int) node->game->score_2;
  t1 = node->game->team_1;
  t2 = node->game->team_2;
  node->game->score_1 = s1;
  node->game->score_2 = s2;
  if (p_s1 > p_s2)
  {
    {
      if (s1 < s2)
      {
        {
          dec_score(t1);
          inc_score(t2);
        }
      }
      else
      {
        
      }

      if (s1 == s2)
      {
        dec_score(t1);
      }
      else
      {
        
      }

    }
  }
  else
  {
    
  }

  if (p_s1 < p_s2)
  {
    {
      if (s1 > s2)
      {
        {
          dec_score(t2);
          inc_score(t1);
        }
      }
      else
      {
        
      }

      if (s1 == s2)
      {
        dec_score(t2);
      }
      else
      {
        
      }

    }
  }
  else
  {
    
  }

  if (p_s1 == p_s2)
  {
    {
      if (s1 > s2)
      {
        inc_score(t1);
      }
      else
      {
        
      }

      if (s1 < s2)
      {
        inc_score(t2);
      }
      else
      {
        
      }

    }
  }
  else
  {
    
  }

}

void insertion_order(game_node node, int NL)
{
  while (node != 0)
  {
    print_game(node, NL);
    node = node->in_next;
  }

}

