#include "/home/fmarques/sbugs/projects/alunos/lib/stubs.h"
/*File generated by PreProcessor.py*/


#include <stdio.h>
#include <string.h>
#include <stdlib.h>


typedef int Integer;
typedef char Character;
typedef struct product
{
  Integer id;
  Character description[64];
  Integer price;
  Integer weight;
  Integer stock;
} Product;
typedef struct order
{
  Integer id;
  Integer selected_products[200];
  Integer chosen_counter;
  Integer quantity[200];
  Integer weight;
} Order;
void create_product();
void add_stock(Integer idP, Integer new_stock);
void create_order();
void add_product(Integer idO, Integer idP, Integer quantity);
void remove_stock(Integer idP, Integer removed_stock);
void remove_product(Integer idO, Integer idP);
void order_cost(Integer idO);
void change_price(Integer idP, Integer price);
void product_amount(Integer idO, Integer idP);
void max_amount(Integer idP);
void sort_products();
void sort_order(Integer idO);
Integer get_quantity(Integer idO, Integer index);
Integer get_price(Integer idP);
void print_Product(Product *product);
void print_Order(Integer idO);
Integer get_price(Integer id);
Integer get_weight_product(Integer id);
Integer get_stock(Integer id);
void set_product_id(Integer id);
void set_price(Integer id, Integer price);
void set_sorted_price(Integer idP, Integer price);
void set_weight_product(Integer id, Integer weight);
void set_stock(Integer id, Integer stock);
void set_sorted_stock(Integer idP, Integer stock);
Integer get_chosenPrd_id(Integer id, Integer index);
Integer get_chosenPrd_count(Integer idO);
Integer get_quantity(Integer id, Integer index);
Integer get_weight_order(Integer id);
void set_order_id(Integer id);
void set_weight_order(Integer id, Integer weight);
void chosen_increment(Integer idO);
void chosen_decrement(Integer idO);
void execute_command(Character selector);
int *get_command();
Integer create_idP();
Integer create_idO();
Integer check_weight(Integer idO, Integer idP, Integer quantity);
void add_weight(Integer idO, Integer idP, Integer quantity);
void remove_weight(Integer idO, Integer idP, Integer quantinty);
Integer check_stock(Integer idP, Integer requested_stock);
void update_quantity(Integer idO, Integer idP, Integer quantity);
Integer valid_product(Integer idP);
Integer valid_order(Integer idO);
void print_Product(Product *product);
void print_Order(Integer idO);
Integer in_order(Integer idO, Integer idP);
Integer find_product(Integer idO, Integer idP);
Integer find_sorted_product(Integer idP);
Product global_products[10000];
Order global_orders[500];
Integer global_idP = 0;
Integer global_idO = 0;
Product global_products_sorted[10000];
Integer global_sort = 0;
int main()
{
  Character selector;
  while (selector != 'x')
  {
    selector = getchar();
    execute_command(selector);
  }

  return 0;
}

void create_product()
{
  Product new_product;
  Character l_description[64];
  Integer l_price = 0;
  Integer l_weight = 0;
  Integer l_stock = 0;
  for (int l_description_index = 0; l_description_index < 10; l_description_index++)
  {
    l_description[l_description_index] = new_sym_var(sizeof(Character) * 8);
  }

  l_price = new_sym_var(sizeof(Integer) * 8);
  l_weight = new_sym_var(sizeof(Integer) * 8);
  l_stock = new_sym_var(sizeof(Integer) * 8);
  new_product.id = create_idP();
  strcpy(new_product.description, l_description);
  new_product.price = l_price;
  new_product.weight = l_weight;
  new_product.stock = l_stock;
  global_products[new_product.id] = new_product;
  printf("%s %d%s\n", "Novo produto", new_product.id, ".");
}

void add_stock(Integer idP, Integer new_stock)
{
  Integer updated_stock;
  updated_stock = global_products[idP].stock + new_stock;
  if (valid_product(idP) == 0)
  {
    set_stock(idP, updated_stock);
    set_sorted_stock(idP, updated_stock);
  }
  else
  {
    printf("%s %d %s\n", "Impossivel adicionar produto", idP, "ao stock. Produto inexistente.");
  }

}

void create_order()
{
  Order new_order;
  new_order.id = create_idO();
  new_order.weight = 0;
  new_order.chosen_counter = 0;
  global_orders[new_order.id] = new_order;
  printf("%s %d%s\n", "Nova encomenda", new_order.id, ".");
}

void add_product(Integer idO, Integer idP, Integer quantity)
{
  if ((((valid_order(idO) == 0) && (valid_product(idP) == 0)) && (check_stock(idP, quantity) == 0)) && (check_weight(idO, idP, quantity) == 0))
  {
    if (in_order(idO, idP) != 0)
    {
      add_weight(idO, idP, quantity);
      global_orders[idO].selected_products[get_chosenPrd_count(idO)] = global_products[idP].id;
      global_orders[idO].quantity[get_chosenPrd_count(idO)] = quantity;
      remove_stock(idP, quantity);
      chosen_increment(idO);
    }
    else
    {
      update_quantity(idO, idP, quantity);
    }

  }
  else
  {
    if (valid_order(idO) == 1)
    {
      printf("%s %d %s %d%s\n", "Impossivel adicionar produto", idP, "a encomenda", idO, ". Encomenda inexistente.");
    }
    else
    {
      if (valid_product(idP) == 1)
      {
        printf("%s %d %s %d%s\n", "Impossivel adicionar produto", idP, "a encomenda", idO, ". Produto inexistente.");
      }
      else
      {
        if (check_stock(idP, quantity) == 1)
        {
          printf("%s %d %s %d%s\n", "Impossivel adicionar produto", idP, "a encomenda", idO, ". Quantidade em stock insuficiente.");
        }
        else
        {
          if (check_weight(idO, idP, quantity) == 1)
          {
            printf("%s %d %s %d%s\n", "Impossivel adicionar produto", idP, "a encomenda", idO, ". Peso da encomenda excede o maximo de 200.");
          }
          else
          {
            
          }

        }

      }

    }

  }

}

void remove_stock(Integer idP, Integer removed_stock)
{
  Integer updated_stock;
  updated_stock = global_products[idP].stock - removed_stock;
  if ((valid_product(idP) == 0) && (updated_stock >= 0))
  {
    set_stock(idP, updated_stock);
    set_sorted_stock(idP, updated_stock);
  }
  else
  {
    if (valid_product(idP) == 1)
    {
      printf("%s %d%s\n", "Impossivel remover stock do produto", idP, ". Produto inexistente.");
    }
    else
    {
      if (updated_stock < 0)
      {
        printf("%s %d %s %d %s\n", "Impossivel remover", removed_stock, "unidades do produto", idP, "do stock. Quantidade insuficiente.");
      }
      else
      {
        
      }

    }

  }

}

void remove_product(Integer idO, Integer idP)
{
  Integer i;
  Integer position;
  Integer quantity;
  if (((valid_order(idO) == 0) && (valid_product(idP) == 0)) && (in_order(idO, idP) == 1))
  {
  }
  else
  {
    if (((valid_order(idO) == 0) && (valid_product(idP) == 0)) && (in_order(idO, idP) == 0))
    {
      position = find_product(idO, idP);
      quantity = get_quantity(idO, position);
      add_stock(idP, quantity);
      remove_weight(idO, idP, quantity);
      for (i = position; i < get_chosenPrd_count(idO); i++)
      {
        global_orders[idO].selected_products[i] = global_orders[idO].selected_products[i + 1];
        global_orders[idO].quantity[i] = global_orders[idO].quantity[i + 1];
      }

      chosen_decrement(idO);
    }
    else
    {
      if (valid_order(idO) == 1)
      {
        printf("%s %d %s %d%s\n", "Impossivel remover produto", idP, "a encomenda", idO, ". Encomenda inexistente.");
      }
      else
      {
        if (valid_product(idP) == 1)
        {
          printf("%s %d %s %d%s\n", "Impossivel remover produto", idP, "a encomenda", idO, ". Produto inexistente.");
        }
        else
        {
          
        }

      }

    }

  }

}

void order_cost(Integer idO)
{
  Integer i;
  Integer total;
  total = 0;
  if (valid_order(idO) == 0)
  {
    for (i = 0; i < get_chosenPrd_count(idO); i++)
    {
      total = total + (get_price(get_chosenPrd_id(idO, i)) * get_quantity(idO, i));
    }

    printf("%s %d %d%s\n", "Custo da encomenda", idO, total, ".");
  }
  else
  {
    printf("%s %d%s\n", "Impossivel calcular custo da encomenda", idO, ". Encomenda inexistente.");
  }

}

void change_price(Integer idP, Integer price)
{
  if (valid_product(idP) == 0)
  {
    set_price(idP, price);
    set_sorted_price(idP, price);
  }
  else
  {
    printf("%s %d%s\n", "Impossivel alterar preco do produto", idP, ". Produto inexistente.");
  }

}

void product_amount(Integer idO, Integer idP)
{
  if ((valid_order(idO) == 0) && (valid_product(idP) == 0))
  {
    if (in_order(idO, idP) == 0)
    {
      printf("%s %d%s\n", global_products[idP].description, get_quantity(idO, find_product(idO, idP)), ".");
    }
    else
    {
      printf("%s %d%s\n", global_products[idP].description, 0, ".");
    }

  }
  else
  {
    if (valid_order(idO) == 1)
    {
      printf("%s %d%s\n", "Impossivel listar encomenda", idO, ". Encomenda inexistente.");
    }
    else
    {
      if (valid_product(idP) == 1)
      {
        printf("%s %d%s\n", "Impossivel listar produto", idP, ". Produto inexistente.");
      }
      else
      {
        
      }

    }

  }

}

void max_amount(Integer idP)
{
  Integer i;
  Integer j;
  Integer id;
  Integer l_id;
  Integer l_ammount;
  l_ammount = 0;
  if (valid_product(idP) == 0)
  {
    for (i = 0; i < global_idO; i++)
    {
      id = global_orders[i].id;
      j = find_product(id, idP);
      if (j != (-1))
      {
        if (l_ammount < get_quantity(id, j))
        {
          l_ammount = get_quantity(id, j);
          l_id = id;
        }
        else
        {
          if (l_ammount == get_quantity(id, j))
          {
            if (id < l_id)
            {
              l_id = id;
            }
            else
            {
              
            }

          }
          else
          {
            
          }

        }

      }
      else
      {
        
      }

    }

    if (l_ammount != 0)
    {
      printf("%s %d %d %d%s\n", "Maximo produto", idP, l_id, l_ammount, ".");
    }
    else
    {
      
    }

  }
  else
  {
    printf("%s %d%s\n", "Impossivel listar maximo do produto", idP, ". Produto inexistente.");
  }

}

void sort_products()
{
  Integer i;
  Integer j;
  Product temp_product;
  if ((sizeof(global_products)) > 1)
  {
    while (global_sort < global_idP)
    {
      global_products_sorted[global_sort] = global_products[global_sort];
      global_sort++;
    }

    for (i = 0; i < global_idP; i++)
    {
      for (j = 0; j < global_idP; j++)
      {
        if (global_products_sorted[j].price > global_products_sorted[i].price)
        {
          temp_product = global_products_sorted[i];
          global_products_sorted[i] = global_products_sorted[j];
          global_products_sorted[j] = temp_product;
        }
        else
        {
          if (global_products_sorted[j].price == global_products_sorted[i].price)
          {
            if (global_products_sorted[j].id > global_products_sorted[i].id)
            {
              temp_product = global_products_sorted[i];
              global_products_sorted[i] = global_products_sorted[j];
              global_products_sorted[j] = temp_product;
            }
            else
            {
              
            }

          }
          else
          {
            
          }

        }

      }

    }

    print_Product(global_products_sorted);
  }
  else
  {
    print_Product(global_products);
  }

}

void sort_order(Integer idO)
{
  Integer i;
  Integer j;
  Integer temp_id;
  Integer temp_quantity;
  if (valid_order(idO) == 0)
  {
    for (i = 0; i < get_chosenPrd_count(idO); i++)
    {
      for (j = 0; j < get_chosenPrd_count(idO); j++)
      {
        if (global_products[get_chosenPrd_id(idO, j)].description[0] > global_products[get_chosenPrd_id(idO, i)].description[0])
        {
          temp_id = global_orders[idO].selected_products[i];
          temp_quantity = global_orders[idO].quantity[i];
          global_orders[idO].selected_products[i] = global_orders[idO].selected_products[j];
          global_orders[idO].selected_products[j] = temp_id;
          global_orders[idO].quantity[i] = global_orders[idO].quantity[j];
          global_orders[idO].quantity[j] = temp_quantity;
        }
        else
        {
          if (global_products[get_chosenPrd_id(idO, j)].description[0] == global_products[get_chosenPrd_id(idO, i)].description[0])
          {
            if (global_products[get_chosenPrd_id(idO, j)].description[1] > global_products[get_chosenPrd_id(idO, i)].description[1])
            {
              temp_id = global_orders[idO].selected_products[i];
              temp_quantity = global_orders[idO].quantity[i];
              global_orders[idO].selected_products[i] = global_orders[idO].selected_products[j];
              global_orders[idO].selected_products[j] = temp_id;
              global_orders[idO].quantity[i] = global_orders[idO].quantity[j];
              global_orders[idO].quantity[j] = temp_quantity;
            }
            else
            {
              
            }

          }
          else
          {
            
          }

        }

      }

    }

    print_Order(idO);
  }
  else
  {
    printf("%s %d%s\n", "Impossivel listar encomenda", idO, ". Encomenda inexistente.");
  }

}

Integer get_price(Integer id)
{
  return global_products[id].price;
}

Integer get_weight_product(Integer id)
{
  return global_products[id].weight;
}

Integer get_stock(Integer id)
{
  return global_products[id].stock;
}

void set_product_id(Integer id)
{
  global_products[id].id = id;
}

void set_price(Integer id, Integer price)
{
  global_products[id].price = price;
}

void set_sorted_price(Integer idP, Integer price)
{
  Integer index;
  index = find_sorted_product(idP);
  if ((global_sort > 0) && (index != (-1)))
  {
    global_products_sorted[index].price = price;
  }
  else
  {
    
  }

}

void set_weight_product(Integer id, Integer weight)
{
  global_products[id].weight = weight;
}

void set_stock(Integer id, Integer stock)
{
  global_products[id].stock = stock;
}

void set_sorted_stock(Integer idP, Integer stock)
{
  Integer index;
  index = find_sorted_product(idP);
  if ((global_sort > 0) && (index != (-1)))
  {
    global_products_sorted[index].stock = stock;
  }
  else
  {
    
  }

}

Integer get_chosenPrd_id(Integer id, Integer index)
{
  return global_orders[id].selected_products[index];
}

Integer get_chosenPrd_count(Integer idO)
{
  return global_orders[idO].chosen_counter;
}

Integer get_quantity(Integer id, Integer index)
{
  return global_orders[id].quantity[index];
}

Integer get_weight_order(Integer id)
{
  return global_orders[id].weight;
}

void set_order_id(Integer id)
{
  global_orders[id].id = id;
}

void set_weight_order(Integer id, Integer weight)
{
  global_orders[id].weight = weight;
}

void execute_command(Character selector)
{
  Integer *command;
  switch (selector)
  {
    case 'a':
      create_product();
      break;

    case 'q':
      command = get_command();
      add_stock(command[0], command[1]);
      break;

    case 'N':
      create_order();
      break;

    case 'A':
      command = get_command();
      add_product(command[0], command[1], command[2]);
      break;

    case 'r':
      command = get_command();
      remove_stock(command[0], command[1]);
      break;

    case 'R':
      command = get_command();
      remove_product(command[0], command[1]);
      break;

    case 'C':
      command = get_command();
      order_cost(command[0]);
      break;

    case 'p':
      command = get_command();
      change_price(command[0], command[1]);
      break;

    case 'E':
      command = get_command();
      product_amount(command[0], command[1]);
      break;

    case 'm':
      command = get_command();
      max_amount(command[0]);
      break;

    case 'l':
      sort_products();
      break;

    case 'L':
      command = get_command();
      sort_order(command[0]);
      break;

    case 'x':
      exit(0);
      break;

    default:
      break;

  }

}

Integer *get_command()
{
  Character command[100];
  Character delim[2] = ":";
  Character *token;
  static Integer split[3];
  Integer i = 0;
  for (int command_index = 0; command_index < 10; command_index++)
  {
    command[command_index] = new_sym_var(sizeof(Character) * 8);
  }

  token = strtok(command, delim);
  while (token != 0)
  {
    split[i++] = atoi(token);
    token = strtok(0, delim);
  }

  return split;
}

Integer create_idP()
{
  Integer new_id;
  new_id = global_idP;
  global_idP++;
  return new_id;
}

Integer create_idO()
{
  Integer new_id;
  new_id = global_idO;
  global_idO++;
  return new_id;
}

Integer check_weight(Integer idO, Integer idP, Integer quantity)
{
  Integer product_w;
  Integer current_w;
  Integer new_w;
  product_w = get_weight_product(idP);
  current_w = get_weight_order(idO);
  new_w = current_w + (product_w * quantity);
  if (new_w <= 200)
  {
    return 0;
  }
  else
  {
    
  }

  return 1;
}

void add_weight(Integer idO, Integer idP, Integer quantity)
{
  Integer product_w;
  Integer current_w;
  Integer new_w;
  product_w = get_weight_product(idP);
  current_w = get_weight_order(idO);
  new_w = current_w + (product_w * quantity);
  set_weight_order(idO, new_w);
}

void remove_weight(Integer idO, Integer idP, Integer quantity)
{
  Integer product_w;
  Integer current_w;
  Integer new_w;
  product_w = get_weight_product(idP);
  current_w = get_weight_order(idO);
  new_w = current_w - (product_w * quantity);
  set_weight_order(idO, new_w);
}

Integer check_stock(Integer idP, Integer requested_stock)
{
  Integer stock;
  stock = get_stock(idP);
  if (stock >= requested_stock)
  {
    return 0;
  }
  else
  {
    
  }

  return 1;
}

void update_quantity(Integer idO, Integer idP, Integer quantity)
{
  Integer index;
  Integer updated_quantity;
  index = find_product(idO, idP);
  updated_quantity = global_orders[idO].quantity[index] + quantity;
  global_orders[idO].quantity[index] = updated_quantity;
  add_weight(idO, idP, quantity);
  remove_stock(idP, quantity);
}

Integer valid_product(Integer idP)
{
  Integer i;
  for (i = 0; i < global_idP; i++)
  {
    if (idP == global_products[i].id)
    {
      return 0;
      break;
    }
    else
    {
      
    }

  }

  return 1;
}

Integer valid_order(Integer idO)
{
  Integer i;
  for (i = 0; i < global_idO; i++)
  {
    if (idO == global_orders[i].id)
    {
      return 0;
      break;
    }
    else
    {
      
    }

  }

  return 1;
}

void print_Product(Product *product)
{
  Integer i;
  printf("%s\n", "Produtos");
  for (i = 0; i < global_idP; i++)
  {
    printf("%s %s %d %d\n", "*", product[i].description, product[i].price, product[i].stock);
  }

}

void print_Order(Integer idO)
{
  Integer i;
  Order order;
  order = global_orders[idO];
  printf("%s %d\n", "Encomenda", order.id);
  if (get_chosenPrd_count(idO) != 0)
  {
    for (i = 0; i < get_chosenPrd_count(idO); i++)
    {
      printf("%s %s %d %d\n", "*", global_products[get_chosenPrd_id(order.id, i)].description, global_products[get_chosenPrd_id(order.id, i)].price, order.quantity[i]);
    }

  }
  else
  {
    
  }

}

void chosen_increment(Integer idO)
{
  global_orders[idO].chosen_counter++;
}

void chosen_decrement(Integer idO)
{
  global_orders[idO].chosen_counter--;
}

Integer in_order(Integer idO, Integer idP)
{
  if (find_product(idO, idP) == (-1))
  {
    return 1;
  }
  else
  {
    
  }

  return 0;
}

Integer find_product(Integer idO, Integer idP)
{
  Integer i;
  i = 0;
  while (i < get_chosenPrd_count(idO))
  {
    if (global_orders[idO].selected_products[i] == idP)
    {
      return i;
      break;
    }
    else
    {
      
    }

    i++;
  }

  return -1;
}

Integer find_sorted_product(Integer idP)
{
  Integer i;
  for (i = 0; i < global_idP; i++)
  {
    if (global_products_sorted[i].id == idP)
    {
      return i;
      break;
    }
    else
    {
      
    }

  }

  return -1;
}

