/*File generated by PreProcessor.py*/


#include <stdio.h>
#include <string.h>
#include <stdlib.h>


typedef struct 
{
  int id;
  char descricao[64];
  int preco;
  int peso;
  int quantStock;
} Produto;
typedef struct 
{
  int id;
  Produto listCompras[10000];
  int pesoTotal;
} Encomenda;
void adicionaProduto();
void adicionaProdEstrutura(Produto prod);
void adicionaStock();
void criaEncomenda();
void colocaProdEncomenda();
void imprimeLstProdutos();
void removeStock();
void alteraPrecoStock();
void listaDescricaoQuantEncomenda();
void calculaCustoEncomenda();
void removeProdEncomenda();
void listaIdpMax();
void imprimelistaComprasAlfabeticamente();
char *ajustaDescricao(Produto prod);
Produto listaProdutos[10000];
Encomenda listaEncomendas[500];
int arrayIndexListProdutos = 0;
int arrayIndexListEncomenda = 0;
int arrayIndexListCompras = 0;
int numEncomenda = 0;
int triggerEncomenda = 0;
int triggerIdpZero = 0;
char novaDescricao[256];
int main()
{
  char comando;
  while (1)
  {
    comando = getchar();
    switch (comando)
    {
      case 'a':
        adicionaProduto();
        break;

      case 'q':
        adicionaStock();
        break;

      case 'N':
        criaEncomenda();
        break;

      case 'A':
        colocaProdEncomenda();
        break;

      case 'r':
        removeStock();
        break;

      case 'R':
        removeProdEncomenda();
        break;

      case 'C':
        calculaCustoEncomenda();
        break;

      case 'p':
        alteraPrecoStock();
        break;

      case 'E':
        listaDescricaoQuantEncomenda();
        break;

      case 'm':
        listaIdpMax();
        break;

      case 'l':
        imprimeLstProdutos();
        break;

      case 'L':
        imprimelistaComprasAlfabeticamente();
        break;

      case 'x':
        return 0;

    }

  }

  return 0;
}

void adicionaProduto()
{
  char input[256];
  char *token;
  const char delim[3] = ":";
  Produto novoProduto;
  int counter = 0;
  fgets(input, sizeof(input), stdin);
  token = strtok(input, delim);
  while (token != 0)
  {
    if (counter == 0)
    {
      strcpy(novoProduto.descricao, token);
    }
    else
    {
      
    }

    if (counter == 1)
    {
      novoProduto.preco = new_sym_var(sizeof(int) * 8);
    }
    else
    {
      
    }

    if (counter == 2)
    {
      novoProduto.peso = new_sym_var(sizeof(int) * 8);
    }
    else
    {
      novoProduto.quantStock = new_sym_var(sizeof(int) * 8);
    }

    counter++;
    token = strtok(0, delim);
  }

  ajustaDescricao(novoProduto);
  printf("Novo produto %d.\n", arrayIndexListProdutos);
  adicionaProdEstrutura(novoProduto);
}

void adicionaStock()
{
  char input[256];
  char *token;
  int count = 0;
  int prodID;
  int prodStock;
  int i;
  int stateConditionIdp = 0;
  fgets(input, sizeof(input), stdin);
  token = strtok(input, ":");
  while (token != 0)
  {
    if (count == 0)
    {
      prodID = new_sym_var(sizeof(int) * 8);
    }
    else
    {
      prodStock = new_sym_var(sizeof(int) * 8);
    }

    count++;
    token = strtok(0, ":");
  }

  for (i = 0; i < arrayIndexListProdutos; i++)
  {
    if (listaProdutos[i].id == prodID)
    {
      listaProdutos[i].quantStock += prodStock;
      stateConditionIdp = 1;
    }
    else
    {
      
    }

  }

  if (stateConditionIdp == 0)
  {
    printf("Impossivel adicionar produto %d ao stock. Produto inexistente.\n", prodID);
  }
  else
  {
    
  }

}

void removeStock()
{
  char input[256];
  char *token;
  int counter = 0;
  int i;
  int prodID;
  int prodRemStock;
  int stateConditionIdp = 0;
  fgets(input, sizeof(input), stdin);
  token = strtok(input, ":");
  while (token != 0)
  {
    if (counter == 0)
    {
      prodID = new_sym_var(sizeof(int) * 8);
    }
    else
    {
      prodRemStock = new_sym_var(sizeof(int) * 8);
    }

    counter++;
    token = strtok(0, ":");
  }

  for (i = 0; i < arrayIndexListProdutos; i++)
  {
    if (listaProdutos[i].id == prodID)
    {
      if (prodRemStock > listaProdutos[i].quantStock)
      {
        printf("Impossivel remover %d unidades do produto %d do stock. Quantidade insuficiente.\n", prodRemStock, prodID);
        return;
      }
      else
      {
        listaProdutos[i].quantStock -= prodRemStock;
        stateConditionIdp = 1;
      }

    }
    else
    {
      
    }

  }

  if (stateConditionIdp == 0)
  {
    printf("Impossivel remover stock do produto %d. Produto inexistente.\n", prodID);
    return;
  }
  else
  {
    
  }

}

void criaEncomenda()
{
  Encomenda novaEncomenda;
  novaEncomenda.id = numEncomenda;
  novaEncomenda.pesoTotal = 0;
  listaEncomendas[numEncomenda] = novaEncomenda;
  arrayIndexListEncomenda++;
  numEncomenda++;
  triggerEncomenda = 1;
  printf("Nova encomenda %d.\n", novaEncomenda.id);
}

void colocaProdEncomenda()
{
  char *token;
  char input[256];
  const char delim[2] = ":";
  int counter = 0;
  int ide;
  int idp;
  int quant;
  int i;
  int j;
  int stateConditionIde = 0;
  int stateConditionIdp = 0;
  fgets(input, sizeof(input), stdin);
  token = strtok(input, delim);
  while (token != 0)
  {
    if (counter == 0)
    {
      ide = new_sym_var(sizeof(int) * 8);
    }
    else
    {
      
    }

    if (counter == 1)
    {
      idp = new_sym_var(sizeof(int) * 8);
    }
    else
    {
      quant = new_sym_var(sizeof(int) * 8);
    }

    counter++;
    token = strtok(0, delim);
  }

  for (i = 0; i < arrayIndexListProdutos; i++)
  {
    if (listaProdutos[i].id == idp)
    {
      if (listaProdutos[i].quantStock != 0)
      {
        if (listaProdutos[i].quantStock < quant)
        {
          printf("Impossivel adicionar produto %d a encomenda %d. Quantidade em stock insuficiente.\n", idp, ide);
          return;
        }
        else
        {
          
        }

      }
      else
      {
        
      }

    }
    else
    {
      
    }

  }

  for (i = 0; i < arrayIndexListEncomenda; i++)
  {
    for (j = 0; j < arrayIndexListProdutos; j++)
    {
      if (listaEncomendas[i].id == ide)
      {
        stateConditionIde = 1;
        if (listaEncomendas[i].listCompras[j].id == idp)
        {
          if (listaProdutos[j].id == idp)
          {
            stateConditionIdp = 1;
            if (((listaEncomendas[i].pesoTotal + (listaProdutos[j].peso * quant)) > 200) && (idp != 0))
            {
              printf("Impossivel adicionar produto %d a encomenda %d. Peso da encomenda excede o maximo de 200.\n", idp, ide);
              return;
            }
            else
            {
              if (idp == 0)
              {
                if (listaProdutos[j].quantStock < quant)
                {
                  printf("Impossivel adicionar produto %d a encomenda %d. Quantidade em stock insuficiente.\n", idp, ide);
                  return;
                }
                else
                {
                  
                }

                if ((listaEncomendas[i].pesoTotal + (listaProdutos[j].peso * quant)) > 200)
                {
                  printf("Impossivel adicionar produto %d a encomenda %d. Peso da encomenda excede o maximo de 200.\n", idp, ide);
                  return;
                }
                else
                {
                  
                }

                triggerIdpZero = 1;
                listaProdutos[j].quantStock -= quant;
                listaEncomendas[i].listCompras[j].quantStock += quant;
                listaEncomendas[i].pesoTotal += listaProdutos[j].peso * quant;
                listaEncomendas[i].listCompras[j].peso = listaProdutos[j].peso;
                listaEncomendas[i].listCompras[j].preco = listaProdutos[j].preco;
                strcpy(listaEncomendas[i].listCompras[j].descricao, listaProdutos[j].descricao);
              }
              else
              {
                if (listaProdutos[j].quantStock < quant)
                {
                  printf("Impossivel adicionar produto %d a encomenda %d. Quantidade em stock insuficiente.\n", idp, ide);
                  return;
                }
                else
                {
                  
                }

                listaProdutos[j].quantStock -= quant;
                listaEncomendas[i].listCompras[j].quantStock += quant;
                listaEncomendas[i].pesoTotal += listaProdutos[j].peso * quant;
              }

            }

          }
          else
          {
            
          }

        }
        else
        {
          if ((listaProdutos[j].id == idp) && (listaEncomendas[i].id == ide))
          {
            stateConditionIdp = 1;
            if (listaProdutos[j].quantStock < quant)
            {
              printf("Impossivel adicionar produto %d a encomenda %d. Quantidade em stock insuficiente.\n", idp, ide);
              return;
            }
            else
            {
              
            }

            if ((listaEncomendas[i].pesoTotal + (listaProdutos[j].peso * quant)) > 200)
            {
              printf("Impossivel adicionar produto %d a encomenda %d. Peso da encomenda excede o maximo de 200.\n", idp, ide);
              return;
            }
            else
            {
              listaProdutos[j].quantStock -= quant;
              listaEncomendas[i].listCompras[j].quantStock += quant;
              listaEncomendas[i].pesoTotal += listaProdutos[j].peso * quant;
              listaEncomendas[i].listCompras[j].id = listaProdutos[j].id;
              listaEncomendas[i].listCompras[j].preco = listaProdutos[j].preco;
              listaEncomendas[i].listCompras[j].peso = listaProdutos[j].peso;
              strcpy(listaEncomendas[i].listCompras[j].descricao, listaProdutos[j].descricao);
            }

          }
          else
          {
            
          }

        }

      }
      else
      {
        
      }

    }

  }

  if ((stateConditionIde == 0) && (stateConditionIdp == 0))
  {
    if (stateConditionIde == 0)
    {
      printf("Impossivel adicionar produto %d a encomenda %d. Encomenda inexistente.\n", idp, ide);
      return;
    }
    else
    {
      
    }

  }
  else
  {
    
  }

  if (stateConditionIdp == 0)
  {
    printf("Impossivel adicionar produto %d a encomenda %d. Produto inexistente.\n", idp, ide);
    return;
  }
  else
  {
    
  }

  if (stateConditionIde == 0)
  {
    printf("Impossivel adicionar produto %d a encomenda %d. Encomenda inexistente.\n", idp, ide);
  }
  else
  {
    
  }

}

void removeProdEncomenda()
{
  char input[256];
  char *token;
  int ide;
  int idp;
  int i;
  int j;
  int counter = 0;
  int stateConditionIde = 0;
  int stateConditionIdp = 0;
  fgets(input, sizeof(input), stdin);
  token = strtok(input, ":");
  while (token != 0)
  {
    if (counter == 0)
    {
      ide = new_sym_var(sizeof(int) * 8);
    }
    else
    {
      idp = new_sym_var(sizeof(int) * 8);
    }

    counter++;
    token = strtok(0, ":");
  }

  for (i = 0; i < arrayIndexListProdutos; i++)
  {
    if (listaProdutos[i].id == idp)
    {
      stateConditionIdp = 1;
    }
    else
    {
      
    }

  }

  for (i = 0; i < arrayIndexListEncomenda; i++)
  {
    for (j = 0; j < arrayIndexListProdutos; j++)
    {
      if (listaEncomendas[i].id == ide)
      {
        stateConditionIde = 1;
        if (listaEncomendas[i].listCompras[j].id == idp)
        {
          listaEncomendas[i].pesoTotal -= listaEncomendas[i].listCompras[j].peso * listaEncomendas[i].listCompras[j].quantStock;
          listaProdutos[j].quantStock += listaEncomendas[i].listCompras[j].quantStock;
          listaEncomendas[i].listCompras[j].quantStock = 0;
          stateConditionIdp = 1;
        }
        else
        {
          
        }

      }
      else
      {
        
      }

    }

  }

  if (stateConditionIde == 0)
  {
    printf("Impossivel remover produto %d a encomenda %d. Encomenda inexistente.\n", idp, ide);
    return;
  }
  else
  {
    
  }

  if (stateConditionIdp == 0)
  {
    printf("Impossivel remover produto %d a encomenda %d. Produto inexistente.\n", idp, ide);
  }
  else
  {
    
  }

}

void listaDescricaoQuantEncomenda()
{
  char *token;
  char input[256];
  int counter = 0;
  int ide;
  int idp;
  int i;
  int j;
  int stateConditionIde = 0;
  int stateConditionIdp = 0;
  fgets(input, sizeof(input), stdin);
  token = strtok(input, ":");
  while (token != 0)
  {
    if (counter == 0)
    {
      ide = new_sym_var(sizeof(int) * 8);
    }
    else
    {
      idp = new_sym_var(sizeof(int) * 8);
    }

    counter++;
    token = strtok(0, ":");
  }

  for (i = 0; i < arrayIndexListEncomenda; i++)
  {
    for (j = 0; j < arrayIndexListProdutos; j++)
    {
      if (listaProdutos[j].id == idp)
      {
        stateConditionIdp = 1;
      }
      else
      {
        
      }

      if (listaEncomendas[i].id == ide)
      {
        stateConditionIde = 1;
      }
      else
      {
        
      }

      if ((stateConditionIdp == 1) && (stateConditionIde == 1))
      {
        if (idp == 0)
        {
          printf("%s %d.\n", ajustaDescricao(listaProdutos[0]), listaEncomendas[ide].listCompras[0].quantStock);
          return;
        }
        else
        {
          
        }

        if (listaEncomendas[ide].listCompras[idp].id == idp)
        {
          printf("%s %d.\n", ajustaDescricao(listaEncomendas[ide].listCompras[idp]), listaEncomendas[ide].listCompras[idp].quantStock);
          return;
        }
        else
        {
          printf("%s %d.\n", ajustaDescricao(listaProdutos[idp]), listaEncomendas[ide].listCompras[idp].quantStock);
          return;
        }

      }
      else
      {
        
      }

    }

  }

  if (stateConditionIdp == 0)
  {
    printf("Impossivel listar produto %d. Produto inexistente.\n", idp);
    return;
  }
  else
  {
    
  }

  if (stateConditionIde == 0)
  {
    printf("Impossivel listar encomenda %d. Encomenda inexistente.\n", ide);
  }
  else
  {
    
  }

}

void calculaCustoEncomenda()
{
  char input[256];
  int ide;
  int i;
  int j;
  int sum = 0;
  int stateConditionIde = 0;
  fgets(input, sizeof(input), stdin);
  ide = new_sym_var(sizeof(int) * 8);
  for (i = 0; i < arrayIndexListEncomenda; i++)
  {
    if ((ide == 0) && (triggerEncomenda == 0))
    {
      printf("Impossivel calcular custo da encomenda %d. Encomenda inexistente.\n", ide);
      return;
    }
    else
    {
      if ((ide == 0) && (triggerEncomenda > 0))
      {
        sum += listaEncomendas[0].listCompras[i].preco * listaEncomendas[0].listCompras[i].quantStock;
        stateConditionIde = 1;
      }
      else
      {
        
      }

    }

    for (j = 0; j < arrayIndexListProdutos; j++)
    {
      if (listaEncomendas[i].id == ide)
      {
        sum += listaEncomendas[i].listCompras[j].preco * listaEncomendas[i].listCompras[j].quantStock;
        stateConditionIde = 1;
      }
      else
      {
        
      }

    }

  }

  if (stateConditionIde == 0)
  {
    printf("Impossivel calcular custo da encomenda %d. Encomenda inexistente.\n", ide);
    return;
  }
  else
  {
    
  }

  printf("Custo da encomenda %d %d.\n", ide, sum);
}

void alteraPrecoStock()
{
  char input[256];
  char *token;
  int i;
  int j;
  int counter = 0;
  int stateConditionIdp = 0;
  int idp;
  int novoPreco;
  fgets(input, sizeof(input), stdin);
  token = strtok(input, ":");
  while (token != 0)
  {
    if (counter == 0)
    {
      idp = new_sym_var(sizeof(int) * 8);
    }
    else
    {
      novoPreco = new_sym_var(sizeof(int) * 8);
    }

    counter++;
    token = strtok(0, ":");
  }

  for (i = 0; i < arrayIndexListProdutos; i++)
  {
    if (listaProdutos[i].id == idp)
    {
      stateConditionIdp = 1;
      listaProdutos[i].preco = novoPreco;
    }
    else
    {
      
    }

  }

  for (j = 0; j < arrayIndexListEncomenda; j++)
  {
    if (listaEncomendas[j].listCompras[idp].id == idp)
    {
      listaEncomendas[j].listCompras[idp].preco = novoPreco;
    }
    else
    {
      
    }

  }

  if (stateConditionIdp == 0)
  {
    printf("Impossivel alterar preco do produto %d. Produto inexistente.\n", idp);
    return;
  }
  else
  {
    
  }

}

void listaIdpMax()
{
  char input[256];
  int i;
  int j;
  int idp;
  int indexEnc;
  int max = 0;
  int stateConditionIdp = 0;
  int stateConditionPrint = 0;
  fgets(input, sizeof(input), stdin);
  idp = new_sym_var(sizeof(int) * 8);
  for (i = 0; i < arrayIndexListProdutos; i++)
  {
    if (listaProdutos[i].id == idp)
    {
      stateConditionIdp = 1;
      break;
    }
    else
    {
      
    }

  }

  for (i = 0; i < arrayIndexListEncomenda; i++)
  {
    for (j = 0; j < arrayIndexListProdutos; j++)
    {
      if (idp == 0)
      {
        if (triggerIdpZero == 0)
        {
          return;
        }
        else
        {
          if (max < listaEncomendas[i].listCompras[idp].quantStock)
          {
            max = listaEncomendas[i].listCompras[idp].quantStock;
            indexEnc = i;
            stateConditionPrint = 1;
          }
          else
          {
            
          }

        }

      }
      else
      {
        if (listaEncomendas[i].listCompras[j].id == idp)
        {
          stateConditionPrint = 1;
          if (max < listaEncomendas[i].listCompras[j].quantStock)
          {
            max = listaEncomendas[i].listCompras[j].quantStock;
            indexEnc = i;
          }
          else
          {
            
          }

        }
        else
        {
          
        }

      }

    }

  }

  if (stateConditionIdp == 0)
  {
    printf("Impossivel listar maximo do produto %d. Produto inexistente.\n", idp);
    return;
  }
  else
  {
    
  }

  if (stateConditionPrint == 1)
  {
    printf("Maximo produto %d %d %d.\n", idp, indexEnc, max);
  }
  else
  {
    
  }

}

void imprimeLstProdutos()
{
  int i;
  int j;
  Produto tmp;
  printf("Produtos\n");
  for (i = 0; i < arrayIndexListProdutos; i++)
  {
    for (j = 0; j < (arrayIndexListProdutos - 1); j++)
    {
      if (listaProdutos[j].preco > listaProdutos[j + 1].preco)
      {
        tmp = listaProdutos[j + 1];
        listaProdutos[j + 1] = listaProdutos[j];
        listaProdutos[j] = tmp;
      }
      else
      {
        if (listaProdutos[j].preco == listaProdutos[j + 1].preco)
        {
          if (listaProdutos[j].id > listaProdutos[j + 1].id)
          {
            tmp = listaProdutos[j + 1];
            listaProdutos[j + 1] = listaProdutos[j];
            listaProdutos[j] = tmp;
          }
          else
          {
            
          }

        }
        else
        {
          
        }

      }

    }

    printf("*%s %d %d\n", listaProdutos[i].descricao, listaProdutos[i].preco, listaProdutos[i].quantStock);
  }

}

void imprimelistaComprasAlfabeticamente()
{
  char input[256];
  int ide;
  int i;
  int stateConditionIde = 0;
  Produto tmp;
  fgets(input, sizeof(input), stdin);
  ide = new_sym_var(sizeof(int) * 8);
  for (i = 0; i < (arrayIndexListProdutos - 1); i++)
  {
    if (strcmp(listaEncomendas[ide].listCompras[i].descricao, listaEncomendas[ide].listCompras[i + 1].descricao) > 0)
    {
      tmp = listaEncomendas[ide].listCompras[i];
      listaEncomendas[ide].listCompras[i] = listaEncomendas[ide].listCompras[i + 1];
      listaEncomendas[ide].listCompras[i + 1] = tmp;
    }
    else
    {
      
    }

    if (ide >= arrayIndexListEncomenda)
    {
      printf("Impossivel listar encomenda %d. Encomenda inexistente.\n", ide);
      return;
    }
    else
    {
      
    }

    if (listaEncomendas[i].id == ide)
    {
      stateConditionIde = 1;
    }
    else
    {
      
    }

  }

  if (stateConditionIde == 0)
  {
    printf("Impossivel listar encomenda %d. Encomenda inexistente.\n", ide);
    return;
  }
  else
  {
    
  }

  if (triggerEncomenda != 1)
  {
    printf("Impossivel listar encomenda %d. Encomenda inexistente.\n", ide);
    return;
  }
  else
  {
    
  }

  printf("Encomenda %d\n", ide);
  for (i = 0; i < arrayIndexListProdutos; i++)
  {
    if (strcmp(listaEncomendas[ide].listCompras[i].descricao, "\0") != 0)
    {
      printf("*%s %d %d\n", listaEncomendas[ide].listCompras[i].descricao, listaEncomendas[ide].listCompras[i].preco, listaEncomendas[ide].listCompras[i].quantStock);
    }
    else
    {
      
    }

  }

}

void adicionaProdEstrutura(Produto prod)
{
  listaProdutos[arrayIndexListProdutos] = prod;
  listaProdutos[arrayIndexListProdutos].id = arrayIndexListProdutos;
  arrayIndexListProdutos++;
}

char *ajustaDescricao(Produto prod)
{
  int i;
  int len;
  len = strlen(prod.descricao);
  for (i = 0; i < len; i++)
  {
    prod.descricao[i] = prod.descricao[i + 1];
  }

  strcpy(novaDescricao, prod.descricao);
  return novaDescricao;
}

