/*File generated by PreProcessor.py*/


#include <stdio.h>
#include <string.h>


typedef struct 
{
  int idp;
  char descricao[63 + 1];
  int preco;
  int peso;
  int quantidade;
} produto;
typedef struct 
{
  int ide;
  produto produto[200];
} encomenda;
typedef produto Item;
produto sistema[10000];
encomenda portofolio[500];
int n_produtos = 0;
int n_encomendas = 0;
void ini_produtos(produto tab[], int dim);
void ini_encomendas(encomenda tab[], int dim);
void adiciona_novo_produto(char desc[], int preco, int peso, int qtd);
void adiciona_stock(int idp, int qtd);
void cria_nova_encomenda();
void adiciona_produto_encomenda(int ide, int idp, int qtd);
void remove_stock(int idp, int qtd);
void remove_produto_encomenda(int ide, int idp);
void calcula_custo(int ide);
void altera_preco(int idp, int preco);
void lista_descricao_quantidade_produto(int ide, int idp);
void lista_identificador_encomenda(int idp);
void lista_produto_sistema();
void lista_produto_encomenda(int ide);
void mergesort(Item arr[], int l, int r, int componente);
void merge(Item a[], int left, int m, int right, int componente);
void k();
void K(int ide);
int main()
{
  int input;
  char desc[63 + 1];
  int preco;
  int peso;
  int qtd;
  int idp;
  int ide;
  ini_produtos(sistema, 10000);
  ini_encomendas(portofolio, 500);
  while ((input = getchar()) != 'x')
  {
    switch (input)
    {
      case 'a':
        for (int desc_index = 0; desc_index < (63 + 1); desc_index++)
      {
        desc[desc_index] = new_sym_var(sizeof(char) * 8);
      }

        desc[(63 + 1) - 1] = '\0';
        preco = new_sym_var(sizeof(int) * 8);
        peso = new_sym_var(sizeof(int) * 8);
        qtd = new_sym_var(sizeof(int) * 8);
        adiciona_novo_produto(desc, preco, peso, qtd);
        break;

      case 'q':
        idp = new_sym_var(sizeof(int) * 8);
        qtd = new_sym_var(sizeof(int) * 8);
        adiciona_stock(idp, qtd);
        break;

      case 'N':
        cria_nova_encomenda();
        break;

      case 'A':
        ide = new_sym_var(sizeof(int) * 8);
        idp = new_sym_var(sizeof(int) * 8);
        qtd = new_sym_var(sizeof(int) * 8);
        adiciona_produto_encomenda(ide, idp, qtd);
        break;

      case 'r':
        idp = new_sym_var(sizeof(int) * 8);
        qtd = new_sym_var(sizeof(int) * 8);
        remove_stock(idp, qtd);
        break;

      case 'R':
        ide = new_sym_var(sizeof(int) * 8);
        idp = new_sym_var(sizeof(int) * 8);
        remove_produto_encomenda(ide, idp);
        break;

      case 'C':
        ide = new_sym_var(sizeof(int) * 8);
        calcula_custo(ide);
        break;

      case 'p':
        idp = new_sym_var(sizeof(int) * 8);
        preco = new_sym_var(sizeof(int) * 8);
        altera_preco(idp, preco);
        break;

      case 'E':
        ide = new_sym_var(sizeof(int) * 8);
        idp = new_sym_var(sizeof(int) * 8);
        lista_descricao_quantidade_produto(ide, idp);
        break;

      case 'm':
        idp = new_sym_var(sizeof(int) * 8);
        lista_identificador_encomenda(idp);
        break;

      case 'l':
        lista_produto_sistema();
        break;

      case 'L':
        ide = new_sym_var(sizeof(int) * 8);
        lista_produto_encomenda(ide);
        break;

    }

    getchar();
  }

  return 0;
}

void ini_produtos(produto tab[], int dim)
{
  int i;
  for (i = 0; i < dim; i++)
  {
    tab[i].idp = -1;
  }

}

void ini_encomendas(encomenda tab[], int dim)
{
  int i;
  for (i = 0; i < dim; i++)
  {
    tab[i].ide = -1;
  }

}

void adiciona_novo_produto(char desc[63 + 1], int preco, int peso, int qtd)
{
  sistema[n_produtos].idp = n_produtos;
  sistema[n_produtos].preco = preco;
  sistema[n_produtos].quantidade = qtd;
  sistema[n_produtos].peso = peso;
  strcpy(sistema[n_produtos].descricao, desc);
  printf("Novo produto %d.\n", n_produtos);
  n_produtos++;
}

void adiciona_stock(int idp, int qtd)
{
  if (sistema[idp].idp == (-1))
  {
    printf("Impossivel adicionar produto %d ao stock. Produto inexistente.\n", idp);
  }
  else
  {
    sistema[idp].quantidade += qtd;
  }

}

void cria_nova_encomenda()
{
  portofolio[n_encomendas].ide = n_encomendas;
  ini_produtos(portofolio[n_encomendas].produto, 200);
  printf("Nova encomenda %d.\n", n_encomendas);
  n_encomendas++;
}

void adiciona_produto_encomenda(int ide, int idp, int qtd)
{
  int i = 0;
  int k = 1;
  int stock;
  int qtd_encomenda;
  int peso_total = 0;
  if (portofolio[ide].ide == (-1))
  {
    printf("Impossivel adicionar produto %d a encomenda %d. Encomenda inexistente.\n", idp, ide);
  }
  else
  {
    if (sistema[idp].idp == (-1))
    {
      printf("Impossivel adicionar produto %d a encomenda %d. Produto inexistente.\n", idp, ide);
    }
    else
    {
      stock = sistema[idp].quantidade;
      qtd_encomenda = stock - qtd;
      if (qtd_encomenda < 0)
      {
        printf("Impossivel adicionar produto %d a encomenda %d. Quantidade em stock insuficiente.\n", idp, ide);
      }
      else
      {
        for (i = 0; i < 200; i++)
        {
          if (portofolio[ide].produto[i].idp != (-1))
          {
            peso_total += portofolio[ide].produto[i].peso * portofolio[ide].produto[i].quantidade;
          }
          else
          {
            
          }

        }

        peso_total = peso_total + (sistema[idp].peso * qtd);
        if (peso_total > 200)
        {
          printf("Impossivel adicionar produto %d a encomenda %d. Peso da encomenda excede o maximo de 200.\n", idp, ide);
        }
        else
        {
          for (i = 0; i < 200; i++)
          {
            if (portofolio[ide].produto[i].idp == idp)
            {
              portofolio[ide].produto[i].quantidade += qtd;
              k = 0;
              break;
            }
            else
            {
              
            }

          }

          if (k)
          {
            for (i = 0; i < 200; i++)
            {
              if (portofolio[ide].produto[i].idp == (-1))
              {
                portofolio[ide].produto[i].idp = sistema[idp].idp;
                portofolio[ide].produto[i].peso = sistema[idp].peso;
                portofolio[ide].produto[i].preco = sistema[idp].preco;
                strcpy(portofolio[ide].produto[i].descricao, sistema[idp].descricao);
                portofolio[ide].produto[i].quantidade = qtd;
                break;
              }
              else
              {
                
              }

            }

          }
          else
          {
            
          }

          sistema[idp].quantidade = qtd_encomenda;
        }

      }

    }

  }

}

void remove_stock(int idp, int qtd)
{
  if (sistema[idp].idp == (-1))
  {
    printf("Impossivel remover stock do produto %d. Produto inexistente.\n", idp);
  }
  else
  {
    if ((sistema[idp].quantidade - qtd) < 0)
    {
      printf("Impossivel remover %d unidades do produto %d do stock. Quantidade insuficiente.\n", qtd, idp);
    }
    else
    {
      sistema[idp].quantidade -= qtd;
    }

  }

}

void remove_produto_encomenda(int ide, int idp)
{
  int i;
  if (portofolio[ide].ide == (-1))
  {
    printf("Impossivel remover produto %d a encomenda %d. Encomenda inexistente.\n", idp, ide);
  }
  else
  {
    if (sistema[idp].idp == (-1))
    {
      printf("Impossivel remover produto %d a encomenda %d. Produto inexistente.\n", idp, ide);
    }
    else
    {
      for (i = 0; i < 200; i++)
      {
        if (portofolio[ide].produto[i].idp == idp)
        {
          sistema[idp].quantidade += portofolio[ide].produto[i].quantidade;
          portofolio[ide].produto[i].idp = -1;
          break;
        }
        else
        {
          
        }

      }

    }

  }

}

void calcula_custo(int ide)
{
  int i;
  int custo = 0;
  if (portofolio[ide].ide == (-1))
  {
    printf("Impossivel calcular custo da encomenda %d. Encomenda inexistente.\n", ide);
  }
  else
  {
    for (i = 0; i < 200; i++)
    {
      if (portofolio[ide].produto[i].idp != (-1))
      {
        custo = custo + (portofolio[ide].produto[i].preco * portofolio[ide].produto[i].quantidade);
      }
      else
      {
        
      }

    }

    printf("Custo da encomenda %d %d.\n", ide, custo);
  }

}

void altera_preco(int idp, int preco)
{
  int i;
  int j;
  if (sistema[idp].idp == (-1))
  {
    printf("Impossivel alterar preco do produto %d. Produto inexistente.\n", idp);
  }
  else
  {
    sistema[idp].preco = preco;
    for (i = 0; i < n_encomendas; i++)
    {
      for (j = 0; j < 200; j++)
      {
        if (portofolio[i].produto[j].idp == idp)
        {
          portofolio[i].produto[j].preco = preco;
        }
        else
        {
          
        }

      }

    }

  }

}

void lista_descricao_quantidade_produto(int ide, int idp)
{
  int i;
  if (portofolio[ide].ide == (-1))
  {
    printf("Impossivel listar encomenda %d. Encomenda inexistente.\n", ide);
  }
  else
  {
    if (sistema[idp].idp == (-1))
    {
      printf("Impossivel listar produto %d. Produto inexistente.\n", idp);
    }
    else
    {
      for (i = 0; i < 200; i++)
      {
        if (portofolio[ide].produto[i].idp == idp)
        {
          printf("%s %d.\n", sistema[idp].descricao, portofolio[ide].produto[i].quantidade);
          break;
        }
        else
        {
          
        }

      }

      if (i == 200)
      {
        printf("%s 0.\n", sistema[idp].descricao);
      }
      else
      {
        
      }

    }

  }

}

void lista_identificador_encomenda(int idp)
{
  int prod_maior_qtd = 0;
  int ide_maior = -1;
  int i;
  int j;
  if (sistema[idp].idp == (-1))
  {
    printf("Impossivel listar maximo do produto %d. Produto inexistente.\n", idp);
  }
  else
  {
    for (i = 0; i < n_encomendas; i++)
    {
      for (j = 0; j < 200; j++)
      {
        if (portofolio[i].produto[j].idp == idp)
        {
          if (portofolio[i].produto[j].quantidade > prod_maior_qtd)
          {
            prod_maior_qtd = portofolio[i].produto[j].quantidade;
            ide_maior = i;
          }
          else
          {
            
          }

        }
        else
        {
          
        }

      }

    }

    if (ide_maior != (-1))
    {
      printf("Maximo produto %d %d %d.\n", idp, ide_maior, prod_maior_qtd);
    }
    else
    {
      
    }

  }

}

void lista_produto_sistema()
{
  int i;
  produto aux_sistema[10000];
  for (i = 0; i < n_produtos; i++)
  {
    aux_sistema[i] = sistema[i];
  }

  mergesort(aux_sistema, 0, n_produtos - 1, 0);
  printf("Produtos\n");
  for (i = 0; i < n_produtos; i++)
  {
    printf("* %s %d %d\n", aux_sistema[i].descricao, aux_sistema[i].preco, aux_sistema[i].quantidade);
  }

}

void lista_produto_encomenda(int ide)
{
  int i;
  int j = 0;
  int n_enc_produtos = 0;
  encomenda encomenda;
  if (portofolio[ide].ide == (-1))
  {
    printf("Impossivel listar encomenda %d. Encomenda inexistente.\n", ide);
  }
  else
  {
    encomenda.ide = portofolio[ide].ide;
    ini_produtos(encomenda.produto, 200);
    for (i = 0; i < 200; i++)
    {
      if (portofolio[ide].produto[i].idp != (-1))
      {
        encomenda.produto[j] = portofolio[ide].produto[i];
        j++;
        n_enc_produtos++;
      }
      else
      {
        
      }

    }

    mergesort(encomenda.produto, 0, n_enc_produtos - 1, 1);
    printf("Encomenda %d\n", ide);
    for (i = 0; i < n_enc_produtos; i++)
    {
      if (encomenda.produto[i].idp != (-1))
      {
        printf("* %s %d %d\n", encomenda.produto[i].descricao, encomenda.produto[i].preco, encomenda.produto[i].quantidade);
      }
      else
      {
        
      }

    }

  }

}

void mergesort(Item arr[], int l, int r, int componente)
{
  if (l < r)
  {
    int m = l + ((r - l) / 2);
    mergesort(arr, l, m, componente);
    mergesort(arr, m + 1, r, componente);
    merge(arr, l, m, r, componente);
  }
  else
  {
    
  }

}

void merge(Item a[], int left, int m, int right, int componente)
{
  int i;
  int j;
  int k;
  int n1 = (m - left) + 1;
  int n2 = right - m;
  Item L[10000];
  Item R[10000];
  for (i = 0; i < n1; i++)
  {
    L[i] = a[left + i];
  }

  for (j = 0; j < n2; j++)
  {
    R[j] = a[(m + 1) + j];
  }

  i = 0;
  j = 0;
  k = left;
  switch (componente)
  {
    case 0:
      while ((i < n1) && (j < n2))
    {
      if (L[i].preco <= R[j].preco)
      {
        a[k] = L[i++];
      }
      else
      {
        a[k] = R[j++];
      }

      k++;
    }

      break;

    case 1:
      while ((i < n1) && (j < n2))
    {
      if (strcmp(L[i].descricao, R[j].descricao) < 0)
      {
        a[k] = L[i++];
      }
      else
      {
        a[k] = R[j++];
      }

      k++;
    }

      break;

  }

  while (i < n1)
  {
    a[k] = L[i++];
    k++;
  }

  while (j < n2)
  {
    a[k] = R[j++];
    k++;
  }

}

void k()
{
  int i;
  for (i = 0; i < n_produtos; i++)
  {
    printf("/%d %s %d %d %d\n", sistema[i].idp, sistema[i].descricao, sistema[i].preco, sistema[i].peso, sistema[i].quantidade);
  }

  printf("\n");
}

void K(int ide)
{
  int i;
  for (i = 0; i < 200; i++)
  {
    if (portofolio[ide].produto[i].idp != (-1))
    {
      printf(":%d:%d %s %d %d %d\n", portofolio[ide].produto[i].idp, i, portofolio[ide].produto[i].descricao, portofolio[ide].produto[i].preco, portofolio[ide].produto[i].quantidade, portofolio[ide].produto[i].peso);
    }
    else
    {
      
    }

  }

  printf("\n");
}

