/*File generated by PreProcessor.py*/


#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "HighFunction.h"


int main()
{
  int programa;
  int nl = 0;
  int golos_equipa1;
  int golos_equipa2;
  char input;
  char nome_equipa1[1023];
  char nome_equipa2[1023];
  char nome_jogo[1023];
  TableJogos *table_jogos = STinitJogo();
  TableEquipas *table_equipas = STinitEquipa();
  linkEquipa equipas = 0;
  linkJogo jogos = 0;
  programa = 1;
  while (programa == 1)
  {
    input = getchar();
    getchar();
    switch (input)
    {
      case 'a':
        nl++;
        for (int nome_jogo_index = 0; nome_jogo_index < 10; nome_jogo_index++)
      {
        nome_jogo[nome_jogo_index] = new_sym_var(sizeof(char) * 8);
      }

        nome_jogo[10 - 1] = '\0';
        for (int nome_equipa1_index = 0; nome_equipa1_index < 10; nome_equipa1_index++)
      {
        nome_equipa1[nome_equipa1_index] = new_sym_var(sizeof(char) * 8);
      }

        nome_equipa1[10 - 1] = '\0';
        for (int nome_equipa2_index = 0; nome_equipa2_index < 10; nome_equipa2_index++)
      {
        nome_equipa2[nome_equipa2_index] = new_sym_var(sizeof(char) * 8);
      }

        nome_equipa2[10 - 1] = '\0';
        golos_equipa1 = new_sym_var(sizeof(int) * 8);
        golos_equipa2 = new_sym_var(sizeof(int) * 8);
        addJogo(table_jogos, jogos, nome_jogo, nome_equipa1, nome_equipa2, golos_equipa1, golos_equipa2);
        printf("%d", nl);
        break;

      case 'A':
        nl++;
        for (int nome_equipa1_index = 0; nome_equipa1_index < 10; nome_equipa1_index++)
      {
        nome_equipa1[nome_equipa1_index] = new_sym_var(sizeof(char) * 8);
      }

        nome_equipa1[10 - 1] = '\0';
        addEquipa(table_equipas, equipas, nome_equipa1);
        printf("%d", nl);
        break;

      case 'l':
        nl++;
        printf("%d", nl);
        break;

      case 'p':
        nl++;
        for (int nome_jogo_index = 0; nome_jogo_index < 10; nome_jogo_index++)
      {
        nome_jogo[nome_jogo_index] = new_sym_var(sizeof(char) * 8);
      }

        nome_jogo[10 - 1] = '\0';
        findJogo(table_jogos, jogos);
        printf("%d", nl);
        break;

      case 'P':
        nl++;
        for (int nome_equipa1_index = 0; nome_equipa1_index < 10; nome_equipa1_index++)
      {
        nome_equipa1[nome_equipa1_index] = new_sym_var(sizeof(char) * 8);
      }

        nome_equipa1[10 - 1] = '\0';
        findEquipa(table_equipas, equipas);
        printf("%d", nl);
        break;

      case 'r':
        nl++;
        for (int nome_jogo_index = 0; nome_jogo_index < 10; nome_jogo_index++)
      {
        nome_jogo[nome_jogo_index] = new_sym_var(sizeof(char) * 8);
      }

        nome_jogo[10 - 1] = '\0';
        removeJogo(table_jogos, jogos);
        printf("%d", nl);
        break;

      case 's':
        nl++;
        for (int nome_jogo_index = 0; nome_jogo_index < 10; nome_jogo_index++)
      {
        nome_jogo[nome_jogo_index] = new_sym_var(sizeof(char) * 8);
      }

        nome_jogo[10 - 1] = '\0';
        golos_equipa1 = new_sym_var(sizeof(int) * 8);
        golos_equipa2 = new_sym_var(sizeof(int) * 8);
        changeScore(table_jogos, jogos, golos_equipa1, golos_equipa2);
        printf("%d", nl);
        break;

      case 'g':
        nl++;
        printf("%d", nl);
        break;

      case 'x':
        programa = 0;

    }

  }

  return 0;
}

