/*File generated by PreProcessor.py*/


#include "structures.h"
#include "auxiliary.h"


int new_team(tlink **team_table, char *name)
{
  int key;
  tlink *aux;
  team *new_team = (team *) malloc(sizeof(team));
  key = stringhash(name);
  aux = team_table[key];
  new_team->name = strdupl(name);
  new_team->victories = 0;
  if (team_table[key] == 0)
  {
    {
      team_table[key] = malloc(sizeof(tlink));
      team_table[key]->next = 0;
      team_table[key]->t = new_team;
      return 1;
    }
  }
  else
  {
    {
      while (aux != 0)
      {
        if (strcmp(aux->t->name, name) == 0)
        {
          {
            free(new_team->name);
            free(new_team);
            return 0;
          }
        }
        else
        {
          
        }

        aux = aux->next;
      }

      aux = malloc(sizeof(tlink));
      aux->next = team_table[key];
      aux->t = new_team;
      team_table[key] = aux;
      return 1;
    }
  }

}

team *team_table_search(tlink **team_table, char *name)
{
  team *result = 0;
  tlink *runthrough;
  int key = stringhash(name);
  for (runthrough = team_table[key]; runthrough != 0; runthrough = runthrough->next)
  {
    if (strcmp(runthrough->t->name, name) == 0)
    {
      {
        result = runthrough->t;
        return result;
      }
    }
    else
    {
      
    }

  }

  return result;
}

void give_victory(tlink **team_table, char *name)
{
  team *winner;
  winner = team_table_search(team_table, name);
  winner->victories++;
}

void remove_victory(tlink **team_table, char *name)
{
  team *loser;
  loser = team_table_search(team_table, name);
  loser->victories--;
}

int compare_func(const void *t1, const void *t2)
{
  team *team1 = (team *) t1;
  team *team2 = (team *) t2;
  return strcmp(team1->name, team2->name);
}

void destroy_ttable(tlink **team_table)
{
  tlink *aux;
  tlink *next;
  int i;
  for (i = 0; i < 419; i++)
  {
    for (aux = team_table[i]; aux != 0; aux = next)
    {
      next = aux->next;
      free(aux->t->name);
      free(aux->t);
      free(aux);
    }

  }

}

void new_game(glink **game_table, tlink **team_table, game **first_game, game **last_game, char *name, char *t1, char *t2, int scr1, int scr2)
{
  int key;
  glink *aux;
  game *new_game = (game *) malloc(sizeof(game));
  key = stringhash(name);
  aux = game_table[key];
  new_game->name = strdupl(name);
  new_game->team1 = strdupl(t1);
  new_game->team2 = strdupl(t2);
  new_game->score1 = scr1;
  new_game->score2 = scr2;
  if (scr1 > scr2)
  {
    give_victory(team_table, t1);
  }
  else
  {
    if (scr2 > scr1)
    {
      give_victory(team_table, t2);
    }
    else
    {
      
    }

  }

  if ((*first_game) == 0)
  {
    {
      new_game->previous = 0;
      new_game->next = 0;
      *last_game = (*first_game = new_game);
    }
  }
  else
  {
    if (first_game[0]->next == 0)
    {
      {
        new_game->previous = *last_game;
        new_game->next = 0;
        last_game[0]->next = new_game;
        first_game[0]->next = new_game;
        *last_game = new_game;
      }
    }
    else
    {
      {
        new_game->previous = *last_game;
        new_game->next = 0;
        last_game[0]->next = new_game;
        *last_game = new_game;
      }
    }

  }

  if (game_table[key] == 0)
  {
    {
      game_table[key] = malloc(sizeof(glink));
      game_table[key]->next = 0;
      game_table[key]->g = new_game;
    }
  }
  else
  {
    {
      while (aux != 0)
        aux = aux->next;

      aux = malloc(sizeof(glink));
      aux->next = game_table[key];
      aux->g = new_game;
      game_table[key] = aux;
    }
  }

}

game *game_table_search(glink **game_table, char *name)
{
  game *result = 0;
  glink *runthrough;
  int key = stringhash(name);
  for (runthrough = game_table[key]; runthrough != 0; runthrough = runthrough->next)
  {
    if (strcmp(runthrough->g->name, name) == 0)
    {
      {
        result = runthrough->g;
        return result;
      }
    }
    else
    {
      
    }

  }

  return result;
}

void delete_game(game **first_game, game **last_game, glink **game_table, tlink **team_table, char *name)
{
  glink *table_aux;
  game *runthrough;
  game *game_aux;
  int key;
  key = stringhash(name);
  table_aux = game_table[key];
  if (strcmp(table_aux->g->name, name) == 0)
  {
    {
      if (table_aux->g->score1 < table_aux->g->score2)
      {
        remove_victory(team_table, table_aux->g->team2);
      }
      else
      {
        if (table_aux->g->score2 < table_aux->g->score1)
        {
          remove_victory(team_table, table_aux->g->team1);
        }
        else
        {
          
        }

      }

      game_table[key] = game_table[key]->next;
      free(table_aux);
    }
  }
  else
  {
    {
      glink *table_prev = 0;
      while (table_aux != 0)
      {
        if (strcmp(table_aux->g->name, name) == 0)
        {
          {
            table_prev->next = table_aux->next;
            if (table_aux->g->score1 < table_aux->g->score2)
            {
              remove_victory(team_table, table_aux->g->team2);
            }
            else
            {
              if (table_aux->g->score2 < table_aux->g->score1)
              {
                remove_victory(team_table, table_aux->g->team1);
              }
              else
              {
                
              }

            }

            table_prev->next = table_aux->next;
            free(table_aux);
            break;
          }
        }
        else
        {
          
        }

        table_prev = table_aux;
        table_aux = table_aux->next;
      }

    }
  }

  runthrough = *first_game;
  if (strcmp(first_game[0]->name, name) == 0)
  {
    {
      if (first_game == last_game)
      {
        {
          *first_game = (*last_game = 0);
          destroy_game(runthrough);
        }
      }
      else
      {
        {
          *first_game = first_game[0]->next;
          destroy_game(runthrough);
        }
      }

    }
  }
  else
  {
    {
      while (runthrough != 0)
      {
        if (strcmp(runthrough->name, name) == 0)
        {
          {
            if (runthrough == (*last_game))
            {
              {
                *last_game = runthrough->previous;
                last_game[0]->next = 0;
                destroy_game(runthrough);
                break;
              }
            }
            else
            {
              {
                game_aux = runthrough->previous;
                game_aux->next = runthrough->next;
                runthrough->next->previous = game_aux;
                destroy_game(runthrough);
                break;
              }
            }

          }
        }
        else
        {
          
        }

        runthrough = runthrough->next;
      }

    }
  }

}

void destroy_game(game *match)
{
  free(match->name);
  free(match->team1);
  free(match->team2);
  free(match);
}

void destroy_gtable(glink **game_table)
{
  glink *aux;
  glink *next;
  int i;
  for (i = 0; i < 419; i++)
  {
    for (aux = game_table[i]; aux != 0; aux = next)
    {
      next = aux->next;
      destroy_game(aux->g);
      free(aux);
    }

  }

}

