/*File generated by PreProcessor.py*/


#include "Equipas.h"
#include "Misc.h"


equipa *cria_equipa(char *nome)
{
  equipa *nova_equipa = (equipa *) malloc(sizeof(equipa));
  nova_equipa->nome = (char *) malloc(strlen(nome) + 1);
  strcpy(nova_equipa->nome, nome);
  nova_equipa->vitorias = 0;
  return nova_equipa;
}

equipa **insere_equipa_h(equipa **h_equipas, equipa *nova_equipa, int *cont_equipas, int *tam_h_equipas)
{
  int i = hash(nova_equipa->nome, *tam_h_equipas);
  while (h_equipas[i])
    i = (i + 1) % (*tam_h_equipas);

  h_equipas[i] = nova_equipa;
  if ((*cont_equipas) > ((*tam_h_equipas) / 2))
  {
    h_equipas = expande_h_equipas(h_equipas, cont_equipas, tam_h_equipas);
  }
  else
  {
    
  }

  return h_equipas;
}

equipa **expande_h_equipas(equipa **h_equipas, int *cont_equipas, int *tam_h_equipas)
{
  int j;
  int novo_tam_h_equipas = 2 * (*tam_h_equipas);
  equipa **aux = (equipa **) calloc(novo_tam_h_equipas, sizeof(equipa *));
  for (j = 0; j < (*tam_h_equipas); j++)
    if (h_equipas[j])
  {
    insere_equipa_h(aux, h_equipas[j], cont_equipas, &novo_tam_h_equipas);
  }
  else
  {
    
  }


  free(h_equipas);
  *tam_h_equipas = novo_tam_h_equipas;
  return aux;
}

equipa *procura_equipa_h(char *nome, equipa **h_equipas, int tam_h_equipas)
{
  int i;
  i = hash(nome, tam_h_equipas);
  while (h_equipas[i])
  {
    if (!strcmp(h_equipas[i]->nome, nome))
    {
      return h_equipas[i];
    }
    else
    {
      
    }

    i = (i + 1) % tam_h_equipas;
  }

  return 0;
}

void destroi_h_equipas(equipa **h_equipas, int tam_h_equipas)
{
  int i;
  for (i = 0; i < tam_h_equipas; i++)
    if (h_equipas[i])
  {
    free(h_equipas[i]->nome);
    free(h_equipas[i]);
  }
  else
  {
    
  }


  free(h_equipas);
}

