/*File generated by PreProcessor.py*/


#include "primary_functions.h"


void add_game(unsigned int ln, game_table *games, team_table *teams)
{
  char *game_name;
  char *team_name_1;
  char *team_name_2;
  int score_1;
  int score_2;
  team *team_1;
  team *team_2;
  getchar();
  game_name = get_string_until(':');
  team_name_1 = get_string_until(':');
  team_name_2 = get_string_until(':');
  score_1 = new_sym_var(sizeof(int) * 8);
  score_2 = new_sym_var(sizeof(int) * 8);
  getchar();
  if (get_game(games, game_name) != 0)
  {
    {
      printf("%d Jogo existente.\n", ln);
      free(game_name);
    }
  }
  else
  {
    if (((team_1 = get_team(teams, team_name_1)) == 0) || ((team_2 = get_team(teams, team_name_2)) == 0))
    {
      {
        printf("%d Equipa inexistente.\n", ln);
        free(game_name);
      }
    }
    else
    {
      {
        new_game(games, game_name, team_1, team_2, score_1, score_2);
        if (score_1 > score_2)
        {
          {
            update_team_wins(team_1, 1);
          }
        }
        else
        {
          if (score_1 < score_2)
          {
            {
              update_team_wins(team_2, 1);
            }
          }
          else
          {
            
          }

        }

      }
    }

  }

  free(team_name_1);
  free(team_name_2);
}

void add_team(unsigned int ln, team_table *teams)
{
  char *name;
  getchar();
  name = get_string_until('\n');
  if (get_team(teams, name) != 0)
  {
    {
      printf("%d Equipa existente.\n", ln);
      free(name);
    }
  }
  else
  {
    {
      new_team(teams, name);
    }
  }

}

void change_game_score(unsigned int ln, game_table *games)
{
  char *name;
  int score_1;
  int score_2;
  game *game;
  team *winner;
  team *new_winner;
  getchar();
  name = get_string_until(':');
  score_1 = new_sym_var(sizeof(int) * 8);
  score_2 = new_sym_var(sizeof(int) * 8);
  getchar();
  if ((game = get_game(games, name)) == 0)
  {
    {
      printf("%d Jogo inexistente.\n", ln);
    }
  }
  else
  {
    {
      winner = game_winner(game);
      update_score(game, score_1, score_2);
      new_winner = game_winner(game);
      if ((winner != 0) && (new_winner != 0))
      {
        {
          if (!same_team(winner, new_winner))
          {
            {
              update_team_wins(winner, -1);
              update_team_wins(new_winner, 1);
            }
          }
          else
          {
            
          }

        }
      }
      else
      {
        if (winner != 0)
        {
          {
            update_team_wins(winner, -1);
          }
        }
        else
        {
          if (new_winner != 0)
          {
            {
              update_team_wins(new_winner, 1);
            }
          }
          else
          {
            
          }

        }

      }

    }
  }

  free(name);
}

void find_game(unsigned int ln, game_table *games)
{
  char *name;
  game *game;
  getchar();
  name = get_string_until('\n');
  if ((game = get_game(games, name)) == 0)
  {
    {
      printf("%d Jogo inexistente.\n", ln);
    }
  }
  else
  {
    {
      printf("%d ", ln);
      print_game(game);
    }
  }

  free(name);
}

void find_team(unsigned int ln, team_table *teams)
{
  char *name;
  team *team;
  getchar();
  name = get_string_until('\n');
  if ((team = get_team(teams, name)) == 0)
  {
    {
      printf("%d Equipa inexistente.\n", ln);
    }
  }
  else
  {
    {
      printf("%d ", ln);
      print_team(team);
    }
  }

  free(name);
}

void list_games(unsigned int ln, game_table *games)
{
  game *game;
  getchar();
  game = first_game(games);
  while (game != 0)
  {
    printf("%d ", ln);
    print_game(game);
    game = next_game(games, game);
  }

}

void list_top_winners(unsigned int ln, team_table *teams)
{
  int i;
  char **team_names;
  getchar();
  team_names = get_top_winners_names(teams);
  if (team_names[0] != 0)
  {
    {
      printf("%d Melhores %d\n", ln, get_max_win_number(teams));
      for (i = 0; team_names[i] != 0; i++)
      {
        printf("%d * %s\n", ln, team_names[i]);
      }

    }
  }
  else
  {
    
  }

}

void remove_game(unsigned int ln, game_table *games)
{
  char *name;
  game *game;
  team *winner;
  getchar();
  name = get_string_until('\n');
  if ((game = get_game(games, name)) == 0)
  {
    {
      printf("%d Jogo inexistente.\n", ln);
    }
  }
  else
  {
    {
      winner = game_winner(game);
      if (winner != 0)
      {
        {
          update_team_wins(winner, -1);
        }
      }
      else
      {
        
      }

      delete_game(games, game);
    }
  }

  free(name);
}

void free_all(game_table *games, team_table *teams)
{
  free_games(games);
  free_teams(teams);
}

char *get_string_until(char stop_char)
{
  int i;
  char c;
  char buffer[1023 + 1];
  char *string;
  for (i = 0; ((c = getchar()) != stop_char) && (i < 1023); i++)
  {
    buffer[i] = c;
  }

  buffer[i] = '\0';
  string = malloc((i + 1) * (sizeof(char)));
  strcpy(string, buffer);
  return string;
}

